/**
 * scripts/bootstrap-obo-conformance-fixture.ts
 *
 * Deterministic, idempotent, test-only OBO conformance fixture seed tool.
 *
 * Reads secrets from a temporary secret bundle (JSON, mode 600), reads the
 * frozen V1 audience definitions from the generated runtime contract, and
 * creates the minimal set of database records needed to exercise the real
 * OBO Token Exchange (RFC 8693) pipeline.
 *
 * Usage:
 *   export DATABASE_URL=postgresql://...
 *   tsx scripts/bootstrap-obo-conformance-fixture.ts \
 *     --secret-bundle /path/to/.secrets.obo.json
 *
 *   # Print manifest without writing:
 *   tsx scripts/bootstrap-obo-conformance-fixture.ts \
 *     --secret-bundle /path/to/.secrets.obo.json --print-manifest
 *
 * Secret bundle format (generated by the harness):
 *   { "callerASecret": "…", "callerBSecret": "…", "adcProxySecret": "…" }
 *
 * Security guarantees:
 *   - Secrets are NEVER written to stdout or logs
 *   - stdout JSON manifest contains only SHA-256 digests of secrets
 *   - All records use upsert for idempotency
 *   - The same secret bundle always produces the same database state
 */

import crypto from 'node:crypto';
import fs from 'node:fs';
import { PrismaClient } from '@prisma/client';
import { hashClientSecret } from '../src/lib/oauth/secret.js';
import {
  initializeAuthContract,
  getV1AudienceDefinitions,
  resetAuthContractForTests,
} from '../src/lib/oauth/v1/contract.js';

// ---------------------------------------------------------------------------
// Fixed deterministic identifiers (never change between runs)
// ---------------------------------------------------------------------------

const CALLER_A_PRINCIPAL_ID  = 'a0000000-0000-4000-8000-000000000001';
const CALLER_B_PRINCIPAL_ID  = 'a0000000-0000-4000-8000-000000000002';
const PROXY_PRINCIPAL_ID     = 'a0000000-0000-4000-8000-000000000003';

const CALLER_A_CLIENT_DB_ID  = 'b0000000-0000-4000-8000-000000000001';
const CALLER_B_CLIENT_DB_ID  = 'b0000000-0000-4000-8000-000000000002';
const PROXY_CLIENT_DB_ID     = 'b0000000-0000-4000-8000-000000000003';

const CALLER_A_CLIENT_ID     = 'caller-a';
const CALLER_B_CLIENT_ID     = 'caller-b';
const PROXY_CLIENT_ID        = 'adc-proxy';

const CALLER_A_AGENT_ID      = 'obo-caller-a-agent';
const CALLER_B_AGENT_ID      = 'obo-caller-b-agent';

const CALLER_A_OWNER_USER_ID = 'c0000000-0000-4000-8000-000000000001';
const CALLER_B_OWNER_USER_ID = 'c0000000-0000-4000-8000-000000000002';

const TRUSTED_PROXY_ID       = 'd0000000-0000-4000-8000-000000000001';

// Negative test entities
// PROXY_CLIENT_PRINCIPAL_MISMATCH: agent-type principal with a TrustedProxy
const MISMATCH_PRINCIPAL_ID  = 'e0000000-0000-4000-8000-000000000001';
const MISMATCH_CLIENT_DB_ID  = 'e0000000-0000-4000-8000-000000000002';
const MISMATCH_CLIENT_ID     = 'mismatch-proxy';
const MISMATCH_TP_ID         = 'e0000000-0000-4000-8000-000000000003';

// UNREGISTERED_PROXY_PRINCIPAL: service-type principal without TrustedProxy
const NO_TP_PRINCIPAL_ID     = 'f0000000-0000-4000-8000-000000000001';
const NO_TP_CLIENT_DB_ID     = 'f0000000-0000-4000-8000-000000000002';
const NO_TP_CLIENT_ID        = 'no-tp-proxy';

// DISABLED_PROXY_REJECTED: service principal + TrustedProxy with status=revoked
const DISABLED_PROXY_PRINCIPAL_ID = 'fa000000-0000-4000-8000-000000000001';
const DISABLED_PROXY_CLIENT_DB_ID = 'fa000000-0000-4000-8000-000000000002';
const DISABLED_PROXY_CLIENT_ID    = 'disabled-proxy';
const DISABLED_TP_ID              = 'fa000000-0000-4000-8000-000000000003';

// MISSING_DELEGATION_GRANT: active service + TrustedProxy but no DelegationGrant for svc-workflow
const NO_DG_PRINCIPAL_ID     = 'fb000000-0000-4000-8000-000000000001';
const NO_DG_CLIENT_DB_ID     = 'fb000000-0000-4000-8000-000000000002';
const NO_DG_CLIENT_ID        = 'no-dg-proxy';
const NO_DG_TP_ID            = 'fb000000-0000-4000-8000-000000000003';

// REVOKED_GRANT: CALLER_C — agent principal whose MachineAccessGrant can be revoked mid-test
const CALLER_C_PRINCIPAL_ID  = 'fc000000-0000-4000-8000-000000000001';
const CALLER_C_CLIENT_DB_ID  = 'fc000000-0000-4000-8000-000000000002';
const CALLER_C_CLIENT_ID     = 'caller-c';
const CALLER_C_AGENT_ID      = 'obo-caller-c-agent';
const CALLER_C_OWNER_USER_ID = 'fc000000-0000-4000-8000-000000000003';

// Human OAuth test constants
const HUMAN_CLIENT_ID          = 'obo-human-client';
const HUMAN_CLIENT_DB_ID       = 'aa000000-0000-4000-8000-000000000001';
const HUMAN_USER_ID            = 'ab000000-0000-4000-8000-000000000001';
const HUMAN_CODE_VERIFIER      = 'test-code-verifier-32bytes-value!';
const HUMAN_CODE_CHALLENGE     = 'fT4yD3k7pLs9vBnM2xR6wG8qH1cJ5uA0eIy3zW8rXo='; // base64url(sha256(verifier))

// ---------------------------------------------------------------------------
// Contract-derived audience scopes (read from runtime, not hardcoded)
// ---------------------------------------------------------------------------

function requiredAudience(audienceId: string) {
  const def = getV1AudienceDefinitions().find((a) => a.audienceId === audienceId);
  if (!def) {
    throw new Error(
      `Frozen contract does not define audience "${audienceId}". ` +
      `Cannot bootstrap fixture.`,
    );
  }
  return def;
}

function validateContractFacts(): void {
  const svcWorkflow = requiredAudience('svc-workflow');
  const adcV2 = requiredAudience('adc-v2');

  // svc-workflow: must support delegated access for agents
  if (!svcWorkflow.delegatedAccessEnabled) {
    throw new Error('svc-workflow must have delegatedAccessEnabled=true in frozen contract.');
  }
  if (!svcWorkflow.acceptedPrincipalTypes.includes('agent')) {
    throw new Error('svc-workflow must accept agent principal type in frozen contract.');
  }
  if (!svcWorkflow.registeredScopes.includes('workflow.read')) {
    throw new Error('svc-workflow must register workflow.read scope.');
  }
  if (!svcWorkflow.registeredScopes.includes('workflow.execute')) {
    throw new Error('svc-workflow must register workflow.execute scope.');
  }

  // adc-v2: must support machine access for agents
  if (!adcV2.machineAccessEnabled) {
    throw new Error('adc-v2 must have machineAccessEnabled=true in frozen contract.');
  }
  if (!adcV2.acceptedPrincipalTypes.includes('agent')) {
    throw new Error('adc-v2 must accept agent principal type in frozen contract.');
  }
  if (!adcV2.registeredScopes.includes('adc.read')) {
    throw new Error('adc-v2 must register adc.read scope.');
  }
}

// ---------------------------------------------------------------------------
// Secret bundle
// ---------------------------------------------------------------------------

interface SecretBundle {
  callerASecret: string;
  callerBSecret: string;
  adcProxySecret: string;
}

function loadSecretBundle(path: string): SecretBundle {
  const raw = fs.readFileSync(path, 'utf8');
  const parsed = JSON.parse(raw) as Record<string, unknown>;
  for (const key of ['callerASecret', 'callerBSecret', 'adcProxySecret']) {
    if (typeof parsed[key] !== 'string' || (parsed[key] as string).length < 16) {
      throw new Error(`Secret bundle missing or invalid field: ${key}`);
    }
  }
  return parsed as SecretBundle;
}

function sha256(value: string): string {
  return crypto.createHash('sha256').update(value).digest('hex');
}

// ---------------------------------------------------------------------------
// Manifest shape (no plaintext secrets)
// ---------------------------------------------------------------------------

interface FixtureManifest {
  contractVersion: string;
  audiences: Array<{ audienceId: string; status: string; scopes: string[] }>;
  principals: Record<string, { id: string; type: string; agentId: string | null }>;
  clients: Record<string, { clientId: string; principalId: string }>;
  trustedProxy: { id: string; proxyPrincipalId: string; proxyClientId: string } | null;
  delegationGrants: Array<{ audienceId: string; scopes: string[] }>;
  acceptedSubjectAudiences: string[];
  // Negative test fixtures
  misMatchProxy: { principalId: string; clientId: string } | null;
  noTpProxy: { principalId: string; clientId: string } | null;
  disabledProxy: { principalId: string; clientId: string } | null;
  noDgProxy: { principalId: string; clientId: string } | null;
  callerC: { principalId: string; clientId: string; agentId: string } | null;
  // Only SHA-256 digests, never plaintext
  secretDigests: Record<string, string>;
}

// ---------------------------------------------------------------------------
// Main
// ---------------------------------------------------------------------------

async function main() {
  // Parse args
  const args = process.argv.slice(2);
  const secretBundleIndex = args.indexOf('--secret-bundle');
  const printManifest = args.includes('--print-manifest');

  if (secretBundleIndex === -1 || secretBundleIndex >= args.length - 1) {
    console.error('Usage: bootstrap-obo-conformance-fixture.ts --secret-bundle <path> [--print-manifest]');
    process.exit(1);
  }

  const secretBundlePath = args[secretBundleIndex + 1];
  const secrets = loadSecretBundle(secretBundlePath);

  // Initialize contract (loads frozen runtime)
  resetAuthContractForTests();
  initializeAuthContract('v1');
  validateContractFacts();

  const svcWorkflow = requiredAudience('svc-workflow');
  const adcV2 = requiredAudience('adc-v2');

  // Build manifest (always built, written if not --print-manifest)
  const manifest: FixtureManifest = {
	    contractVersion: '1.2.0',
    audiences: [
      { audienceId: 'svc-workflow', status: svcWorkflow.status, scopes: [...svcWorkflow.registeredScopes] },
      { audienceId: 'adc-v2', status: adcV2.status, scopes: [...adcV2.registeredScopes] },
    ],
    principals: {
      callerA: { id: CALLER_A_PRINCIPAL_ID, type: 'agent', agentId: CALLER_A_AGENT_ID },
      callerB: { id: CALLER_B_PRINCIPAL_ID, type: 'agent', agentId: CALLER_B_AGENT_ID },
      adcProxy: { id: PROXY_PRINCIPAL_ID, type: 'service', agentId: null },
    },
    clients: {
      callerA: { clientId: CALLER_A_CLIENT_ID, principalId: CALLER_A_PRINCIPAL_ID },
      callerB: { clientId: CALLER_B_CLIENT_ID, principalId: CALLER_B_PRINCIPAL_ID },
      adcProxy: { clientId: PROXY_CLIENT_ID, principalId: PROXY_PRINCIPAL_ID },
    },
    trustedProxy: {
      id: TRUSTED_PROXY_ID,
      proxyPrincipalId: PROXY_PRINCIPAL_ID,
      proxyClientId: PROXY_CLIENT_DB_ID,
    },
    delegationGrants: [
      { audienceId: 'svc-workflow', scopes: ['workflow.execute', 'workflow.read'] },
    ],
    acceptedSubjectAudiences: ['adc-v2'],
    misMatchProxy: {
      principalId: MISMATCH_PRINCIPAL_ID,
      clientId: MISMATCH_CLIENT_ID,
    },
    noTpProxy: {
      principalId: NO_TP_PRINCIPAL_ID,
      clientId: NO_TP_CLIENT_ID,
    },
    disabledProxy: {
      principalId: DISABLED_PROXY_PRINCIPAL_ID,
      clientId: DISABLED_PROXY_CLIENT_ID,
    },
    noDgProxy: {
      principalId: NO_DG_PRINCIPAL_ID,
      clientId: NO_DG_CLIENT_ID,
    },
    callerC: {
      principalId: CALLER_C_PRINCIPAL_ID,
      clientId: CALLER_C_CLIENT_ID,
      agentId: CALLER_C_AGENT_ID,
    },
    secretDigests: {
      callerA: sha256(secrets.callerASecret),
      callerB: sha256(secrets.callerBSecret),
      adcProxy: sha256(secrets.adcProxySecret),
    },
  };

  if (printManifest) {
    process.stdout.write(`${JSON.stringify(manifest, null, 2)}\n`);
    return;
  }

  // -----------------------------------------------------------------------
  // Seed database
  // -----------------------------------------------------------------------

  const prisma = new PrismaClient();

  try {
    await prisma.$transaction(async (tx) => {
      // 1. AuthAudience records (from frozen contract)
      for (const audience of [svcWorkflow, adcV2]) {
        await tx.authAudience.upsert({
          where: { audienceId: audience.audienceId },
          update: {
            resourceService: audience.resourceService,
            scopeNamespace: audience.scopeNamespace,
            acceptedPrincipalTypes: [...audience.acceptedPrincipalTypes],
            registeredScopes: [...audience.registeredScopes],
            humanAccessEnabled: audience.humanAccessEnabled,
            machineAccessEnabled: audience.machineAccessEnabled,
            delegatedAccessEnabled: audience.delegatedAccessEnabled,
            status: audience.status,
            freezeReady: audience.freezeReady,
            version: 1,
          },
          create: {
            audienceId: audience.audienceId,
            resourceService: audience.resourceService,
            scopeNamespace: audience.scopeNamespace,
            acceptedPrincipalTypes: [...audience.acceptedPrincipalTypes],
            registeredScopes: [...audience.registeredScopes],
            humanAccessEnabled: audience.humanAccessEnabled,
            machineAccessEnabled: audience.machineAccessEnabled,
            delegatedAccessEnabled: audience.delegatedAccessEnabled,
            status: audience.status,
            freezeReady: audience.freezeReady,
            version: 1,
          },
        });
      }

      // 2. Owner users (minimal records for FK constraints)
      for (const [userId, userName] of [
        [CALLER_A_OWNER_USER_ID, 'OBO Conformance CALLER_A Owner'],
        [CALLER_B_OWNER_USER_ID, 'OBO Conformance CALLER_B Owner'],
        [CALLER_C_OWNER_USER_ID, 'OBO Conformance CALLER_C Owner'],
      ] as const) {
        await tx.user.upsert({
          where: { id: userId },
          update: { name: userName },
          create: {
            id: userId,
            name: userName,
            email: `${userId}@obo-conformance.test.local`,
            password: 'obo-conformance-test-pw',
            role: 'agent',
          },
        });
      }

      // 3. Machine principals
      type PrincipalInput = {
        id: string; principalType: 'agent' | 'service'; agentId: string | null; ownerUserId: string | null;
        displayName: string;
      };
      const principals: PrincipalInput[] = [
        { id: CALLER_A_PRINCIPAL_ID, principalType: 'agent', agentId: CALLER_A_AGENT_ID, ownerUserId: CALLER_A_OWNER_USER_ID, displayName: 'OBO CALLER_A' },
        { id: CALLER_B_PRINCIPAL_ID, principalType: 'agent', agentId: CALLER_B_AGENT_ID, ownerUserId: CALLER_B_OWNER_USER_ID, displayName: 'OBO CALLER_B' },
        { id: PROXY_PRINCIPAL_ID, principalType: 'service', agentId: null, ownerUserId: null, displayName: 'OBO ADC Proxy' },
        // Negative test principals
        { id: MISMATCH_PRINCIPAL_ID, principalType: 'agent', agentId: 'mismatch-agent', ownerUserId: CALLER_A_OWNER_USER_ID, displayName: 'OBO Mismatch Proxy (agent)' },
        { id: NO_TP_PRINCIPAL_ID, principalType: 'service', agentId: null, ownerUserId: null, displayName: 'OBO No-TP Proxy (service)' },
        { id: DISABLED_PROXY_PRINCIPAL_ID, principalType: 'service', agentId: null, ownerUserId: null, displayName: 'OBO Disabled Proxy' },
        { id: NO_DG_PRINCIPAL_ID, principalType: 'service', agentId: null, ownerUserId: null, displayName: 'OBO No-DG Proxy' },
        { id: CALLER_C_PRINCIPAL_ID, principalType: 'agent', agentId: CALLER_C_AGENT_ID, ownerUserId: CALLER_C_OWNER_USER_ID, displayName: 'OBO CALLER_C' },
      ];
      for (const p of principals) {
        await tx.machinePrincipal.upsert({
          where: { id: p.id },
          update: { principalType: p.principalType, agentId: p.agentId, ownerUserId: p.ownerUserId, displayName: p.displayName },
          create: { ...p },
        });
      }

      // 4. Machine clients
      type ClientInput = {
        id: string; clientId: string; machinePrincipalId: string; secretHash: string;
      };
      // Negative test clients share the same secret bundle's adcProxySecret for simplicity
      const clients: ClientInput[] = [
        { id: CALLER_A_CLIENT_DB_ID, clientId: CALLER_A_CLIENT_ID, machinePrincipalId: CALLER_A_PRINCIPAL_ID, secretHash: hashClientSecret(secrets.callerASecret) },
        { id: CALLER_B_CLIENT_DB_ID, clientId: CALLER_B_CLIENT_ID, machinePrincipalId: CALLER_B_PRINCIPAL_ID, secretHash: hashClientSecret(secrets.callerBSecret) },
        { id: PROXY_CLIENT_DB_ID, clientId: PROXY_CLIENT_ID, machinePrincipalId: PROXY_PRINCIPAL_ID, secretHash: hashClientSecret(secrets.adcProxySecret) },
        { id: MISMATCH_CLIENT_DB_ID, clientId: MISMATCH_CLIENT_ID, machinePrincipalId: MISMATCH_PRINCIPAL_ID, secretHash: hashClientSecret(secrets.adcProxySecret) },
        { id: NO_TP_CLIENT_DB_ID, clientId: NO_TP_CLIENT_ID, machinePrincipalId: NO_TP_PRINCIPAL_ID, secretHash: hashClientSecret(secrets.adcProxySecret) },
        { id: DISABLED_PROXY_CLIENT_DB_ID, clientId: DISABLED_PROXY_CLIENT_ID, machinePrincipalId: DISABLED_PROXY_PRINCIPAL_ID, secretHash: hashClientSecret(secrets.adcProxySecret) },
        { id: NO_DG_CLIENT_DB_ID, clientId: NO_DG_CLIENT_ID, machinePrincipalId: NO_DG_PRINCIPAL_ID, secretHash: hashClientSecret(secrets.adcProxySecret) },
        { id: CALLER_C_CLIENT_DB_ID, clientId: CALLER_C_CLIENT_ID, machinePrincipalId: CALLER_C_PRINCIPAL_ID, secretHash: hashClientSecret(secrets.adcProxySecret) },
      ];
      for (const c of clients) {
        await tx.machineClient.upsert({
          where: { clientId: c.clientId },
          update: {
            machinePrincipalId: c.machinePrincipalId,
            secretHash: c.secretHash,
            status: 'active',
          },
          create: {
            id: c.id,
            clientId: c.clientId,
            machinePrincipalId: c.machinePrincipalId,
            secretHash: c.secretHash,
            status: 'active',
            allowedResources: [],
            allowedScopes: [],
          },
        });
      }

      // 5. MachineAccessGrants
      // CALLER_A: adc-v2:adc.read (for Subject Token)
      await tx.machineAccessGrant.upsert({
        where: { machineClientId_audienceId: { machineClientId: CALLER_A_CLIENT_DB_ID, audienceId: 'adc-v2' } },
        update: { scopes: ['adc.read'], version: 1 },
        create: { machineClientId: CALLER_A_CLIENT_DB_ID, audienceId: 'adc-v2', scopes: ['adc.read'], version: 1 },
      });
      // CALLER_A: svc-workflow:workflow.read,workflow.execute (for OBO exchange)
      await tx.machineAccessGrant.upsert({
        where: { machineClientId_audienceId: { machineClientId: CALLER_A_CLIENT_DB_ID, audienceId: 'svc-workflow' } },
        update: { scopes: ['workflow.execute', 'workflow.read'], version: 1 },
        create: { machineClientId: CALLER_A_CLIENT_DB_ID, audienceId: 'svc-workflow', scopes: ['workflow.execute', 'workflow.read'], version: 1 },
      });
      // CALLER_B: adc-v2:adc.read (for Subject Token only, NO svc-workflow grant)
      await tx.machineAccessGrant.upsert({
        where: { machineClientId_audienceId: { machineClientId: CALLER_B_CLIENT_DB_ID, audienceId: 'adc-v2' } },
        update: { scopes: ['adc.read'], version: 1 },
        create: { machineClientId: CALLER_B_CLIENT_DB_ID, audienceId: 'adc-v2', scopes: ['adc.read'], version: 1 },
      });
      // Note: CALLER_B has NO MachineAccessGrant for svc-workflow — negative test

      // CALLER_C: adc-v2:adc.read (for Subject Token)
      await tx.machineAccessGrant.upsert({
        where: { machineClientId_audienceId: { machineClientId: CALLER_C_CLIENT_DB_ID, audienceId: 'adc-v2' } },
        update: { scopes: ['adc.read'], version: 1 },
        create: { machineClientId: CALLER_C_CLIENT_DB_ID, audienceId: 'adc-v2', scopes: ['adc.read'], version: 1 },
      });
      // CALLER_C: svc-workflow:workflow.read,workflow.execute (revokable grant for REVOKED_GRANT test)
      await tx.machineAccessGrant.upsert({
        where: { machineClientId_audienceId: { machineClientId: CALLER_C_CLIENT_DB_ID, audienceId: 'svc-workflow' } },
        update: { scopes: ['workflow.execute', 'workflow.read'], version: 1 },
        create: { machineClientId: CALLER_C_CLIENT_DB_ID, audienceId: 'svc-workflow', scopes: ['workflow.execute', 'workflow.read'], version: 1 },
      });

      // 6. TrustedProxy records
      // 6a. ADC_PROXY TrustedProxy (positive path)
      await tx.trustedProxy.upsert({
        where: { id: TRUSTED_PROXY_ID },
        update: {
          proxyPrincipalId: PROXY_PRINCIPAL_ID,
          proxyClientId: PROXY_CLIENT_DB_ID,
          status: 'active',
          version: 1,
        },
        create: {
          id: TRUSTED_PROXY_ID,
          proxyPrincipalId: PROXY_PRINCIPAL_ID,
          proxyClientId: PROXY_CLIENT_DB_ID,
          status: 'active',
          version: 1,
        },
      });

      // 6b. MISMATCH TrustedProxy (agent-type principal — tests PROXY_CLIENT_PRINCIPAL_MISMATCH)
      await tx.trustedProxy.upsert({
        where: { id: MISMATCH_TP_ID },
        update: {
          proxyPrincipalId: MISMATCH_PRINCIPAL_ID,
          proxyClientId: MISMATCH_CLIENT_DB_ID,
          status: 'active',
          version: 1,
        },
        create: {
          id: MISMATCH_TP_ID,
          proxyPrincipalId: MISMATCH_PRINCIPAL_ID,
          proxyClientId: MISMATCH_CLIENT_DB_ID,
          status: 'active',
          version: 1,
        },
      });
      // NO_TP proxy has NO TrustedProxy — tests UNREGISTERED_PROXY_PRINCIPAL

      // 6c. DISABLED TrustedProxy (revoked status — tests DISABLED_PROXY_REJECTED)
      await tx.trustedProxy.upsert({
        where: { id: DISABLED_TP_ID },
        update: {
          proxyPrincipalId: DISABLED_PROXY_PRINCIPAL_ID,
          proxyClientId: DISABLED_PROXY_CLIENT_DB_ID,
          status: 'revoked',
          version: 1,
        },
        create: {
          id: DISABLED_TP_ID,
          proxyPrincipalId: DISABLED_PROXY_PRINCIPAL_ID,
          proxyClientId: DISABLED_PROXY_CLIENT_DB_ID,
          status: 'revoked',
          version: 1,
        },
      });

      // 6d. NO-DG TrustedProxy (active but no DelegationGrant for svc-workflow)
      await tx.trustedProxy.upsert({
        where: { id: NO_DG_TP_ID },
        update: {
          proxyPrincipalId: NO_DG_PRINCIPAL_ID,
          proxyClientId: NO_DG_CLIENT_DB_ID,
          status: 'active',
          version: 1,
        },
        create: {
          id: NO_DG_TP_ID,
          proxyPrincipalId: NO_DG_PRINCIPAL_ID,
          proxyClientId: NO_DG_CLIENT_DB_ID,
          status: 'active',
          version: 1,
        },
      });

      // 7. ProxyAcceptedSubjectAudience (accepts adc-v2 subject tokens)
      for (const tpId of [TRUSTED_PROXY_ID, MISMATCH_TP_ID, DISABLED_TP_ID, NO_DG_TP_ID]) {
        await tx.proxyAcceptedSubjectAudience.upsert({
          where: { trustedProxyId_audienceId: { trustedProxyId: tpId, audienceId: 'adc-v2' } },
          update: {},
          create: { trustedProxyId: tpId, audienceId: 'adc-v2' },
        });
      }

      // 8. DelegationGrant (proxy can delegate workflow.read, workflow.execute)
      // DISABLED and NO_DG proxies do NOT get a DelegationGrant for svc-workflow
      for (const tpId of [TRUSTED_PROXY_ID, MISMATCH_TP_ID]) {
        await tx.delegationGrant.upsert({
          where: { trustedProxyId_audienceId: { trustedProxyId: tpId, audienceId: 'svc-workflow' } },
          update: { scopes: ['workflow.execute', 'workflow.read'], version: 1 },
          create: { trustedProxyId: tpId, audienceId: 'svc-workflow', scopes: ['workflow.execute', 'workflow.read'], version: 1 },
        });
      }

      // 9. Human OAuth fixtures (for HUMAN_OBO test)
      // 9a. User for human auth
      await tx.user.upsert({
        where: { id: HUMAN_USER_ID },
        update: { name: 'OBO Human Test User' },
        create: {
          id: HUMAN_USER_ID,
          name: 'OBO Human Test User',
          email: 'obo-human@obo-conformance.test.local',
          password: 'obo-placeholder-' + crypto.randomUUID().slice(0,8),
          role: 'agent',
        },
      });

      // 9b. HumanClient (confidential web client)
      await tx.humanClient.upsert({
        where: { clientId: HUMAN_CLIENT_ID },
        update: {
          clientType: 'confidential_web',
          clientAuthenticationMethod: 'client_secret_basic',
          credentialVerifier: '$2b$10$obo.conformance.test.hash.placeholder',
          status: 'active',
          version: 1,
        },
        create: {
          id: HUMAN_CLIENT_DB_ID,
          clientId: HUMAN_CLIENT_ID,
          clientType: 'confidential_web',
          clientAuthenticationMethod: 'client_secret_basic',
          credentialVerifier: '$2b$10$obo.conformance.test.hash.placeholder',
          status: 'active',
          version: 1,
        },
      });

      // 9c. Redirect URI
      await tx.humanClientRedirectUri.upsert({
        where: { humanClientId_redirectUri: { humanClientId: HUMAN_CLIENT_DB_ID, redirectUri: 'http://localhost:9999/callback' } },
        update: {},
        create: { humanClientId: HUMAN_CLIENT_DB_ID, redirectUri: 'http://localhost:9999/callback' },
      });

      // 9d. AuthorizationTransaction (pre-authenticated)
      const txId = 'ac000000-0000-4000-8000-000000000001';
      await tx.authorizationTransaction.upsert({
        where: { id: txId },
        update: {
          humanClientId: HUMAN_CLIENT_DB_ID,
          audienceId: 'svc-workflow',
          redirectUri: 'http://localhost:9999/callback',
          state: 'test-state',
          codeChallenge: HUMAN_CODE_CHALLENGE,
          codeChallengeMethod: 'S256',
          authenticatedUserId: HUMAN_USER_ID,
          status: 'authenticated',
          expiresAt: new Date(Date.now() + 3600000),
          version: 1,
        },
        create: {
          id: txId,
          humanClientId: HUMAN_CLIENT_DB_ID,
          audienceId: 'svc-workflow',
          redirectUri: 'http://localhost:9999/callback',
          state: 'test-state',
          codeChallenge: HUMAN_CODE_CHALLENGE,
          codeChallengeMethod: 'S256',
          authenticatedUserId: HUMAN_USER_ID,
          status: 'authenticated',
          expiresAt: new Date(Date.now() + 3600000),
          version: 1,
        },
      });

      // 9e. AuthorizationCode
      const codeId = 'ad000000-0000-4000-8000-000000000001';
      const codeVerifierB64 = Buffer.from(HUMAN_CODE_VERIFIER).toString('base64url');
      const codeValue = `ac1.${codeId}.${codeVerifierB64}`;
      await tx.authorizationCode.upsert({
        where: { id: codeId },
        update: {
          credentialVerifier: codeValue,
          verifierParametersVersion: 'pkce-v1',
          authorizationTransactionId: txId,
          userId: HUMAN_USER_ID,
          humanClientId: HUMAN_CLIENT_DB_ID,
          audienceId: 'svc-workflow',
          redirectUri: 'http://localhost:9999/callback',
          status: 'active',
          issuedAt: new Date(),
          expiresAt: new Date(Date.now() + 3600000),
          version: 1,
        },
        create: {
          id: codeId,
          credentialVerifier: codeValue,
          verifierParametersVersion: 'pkce-v1',
          authorizationTransactionId: txId,
          userId: HUMAN_USER_ID,
          humanClientId: HUMAN_CLIENT_DB_ID,
          audienceId: 'svc-workflow',
          redirectUri: 'http://localhost:9999/callback',
          status: 'active',
          issuedAt: new Date(),
          expiresAt: new Date(Date.now() + 3600000),
          version: 1,
        },
      });
    });

    // Verify — read back and confirm record counts
    const [
      audiences, principals, clients, grants, trustedProxies,
    ] = await Promise.all([
      prisma.authAudience.findMany({ orderBy: { audienceId: 'asc' } }),
      prisma.machinePrincipal.findMany({ orderBy: { id: 'asc' } }),
      prisma.machineClient.findMany({ orderBy: { clientId: 'asc' } }),
      prisma.machineAccessGrant.findMany({ orderBy: [{ machineClientId: 'asc' }, { audienceId: 'asc' }] }),
      prisma.trustedProxy.findMany(),
    ]);

    const acceptedAudiences = await prisma.proxyAcceptedSubjectAudience.findMany();
    const delegationGrants = await prisma.delegationGrant.findMany();

    const verified = {
      audienceCount: audiences.length,
      principalCount: principals.length,
      clientCount: clients.length,
      accessGrantCount: grants.length,
      trustedProxyCount: trustedProxies.length,
      acceptedAudienceCount: acceptedAudiences.length,
      delegationGrantCount: delegationGrants.length,
      callerAHassvcWorkflowGrant: grants.some(
        (g) => g.machineClientId === CALLER_A_CLIENT_DB_ID && g.audienceId === 'svc-workflow',
      ),
      callerBHassvcWorkflowGrant: grants.some(
        (g) => g.machineClientId === CALLER_B_CLIENT_DB_ID && g.audienceId === 'svc-workflow',
      ),
    };

    process.stdout.write(
      `${JSON.stringify({ manifest, verified }, null, 2)}\n`,
    );
  } finally {
    await prisma.$disconnect();
  }
}

main().catch((error) => {
  console.error((error as Error).message);
  process.exitCode = 1;
});
