import { createHash, randomBytes, randomUUID, scryptSync, timingSafeEqual } from 'node:crypto';
import { execFileSync } from 'node:child_process';
import {
  chmodSync, closeSync, existsSync, fchmodSync, fstatSync, fsyncSync, lstatSync, mkdirSync,
  openSync, readFileSync, readSync, realpathSync, renameSync, unlinkSync, writeSync,
} from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import type { Stats } from 'node:fs';
import { Prisma, PrismaClient } from '@prisma/client';

/*
 * Closed operator for AUTH_SERVICE_AGENT_CORE_NOTIFICATION_INGRESS_SERVICE_CREDENTIAL_GRANT_V1.
 * Default = read-only plan. Production apply is impossible without a clean exact HEAD, accepted
 * Spec, an exact plan file+digest, and a FIFO-delivered owner approval bound to this environment,
 * implementation, digest and execution window. Conformance has a separate descriptor-only seam.
 */
const ROOT = fileURLToPath(new URL('../', import.meta.url));
const SPEC_ID = 'AUTH_SERVICE_AGENT_CORE_NOTIFICATION_INGRESS_SERVICE_CREDENTIAL_GRANT_V1';
const SPEC_PATH = `docs/specs/${SPEC_ID}.md`;
const PLAN_VERSION = `${SPEC_ID}_PLAN_1`;
const MIGRATION_ID = 'notification-ingress-service-credential-grant-v1';
const AUDIENCE_ID = 'agent-core-notification-ingress-v1';
const SCOPE = 'notification.deliver';
const GLOBAL_LOCK = 741_903_511;
const PROD_CONFIRMATION = 'AUTHORIZED_NOTIFICATION_INGRESS_PHASE_B_APPLY_V1';
const REPORT_KEYS = ['schema_version', 'operation', 'result', 'plan_sha256', 'classification', 'writes', 'non_target_digest', 'residual_coordinates'] as const;
const AUDIT_KEYS = ['change_id', 'migration_id', 'source_git_commit', 'operator_id', 'approval_ref', 'reason', 'client_id', 'change_type', 'expected_grant_version', 'resulting_grant_version', 'before_value', 'after_value', 'timestamp'] as const;

type Json = null | boolean | number | string | Json[] | { [key: string]: Json };
type Db = PrismaClient | Prisma.TransactionClient;
type Target = {
  caller: 'svc-forum' | 'svc-workflow'; principalExternalRef: string; principalDisplayName: string;
  clientExternalRef: string; clientId: string; productionDestination: string;
};
type Destination = { path: string; exists: boolean; mode: number | null; uid: number | null; keys: string[]; exact: boolean; secret: string | null; bytes: Buffer | null };
type Approval = { spec_id: string; spec_revision: string; implementation_commit: string; plan_sha256: string; environment: string; window_not_before: string; window_not_after: string; operator_id: string; approval_ref: string };
type Context = { url: string; environment: string; destinations: Record<string, string>; expectedUid: number; markerPath: string; conformance: boolean; faultInjection: 'none' | 'after-install-and-restore-fail' };
type TargetState = { classification: 'ABSENT' | 'EXACT_RERUN_NOOP'; safe: Json; internalIds: Record<string, string>; secretHashes: Record<string, string>; audits: Json[] };
type Live = { databaseIdentity: { database: string; address: string; port: number }; audience: Json; targets: TargetState; destinations: Json[]; destinationRuntime: Destination[]; nonTargetDigest: string; nonTargetCounts: { clients: number; grants: number } };
type Plan = { plan_version: string; spec_id: string; spec_revision: string; implementation_commit: string; environment: string; database_identity: { database: string; address: string; port: number }; classification: 'CREATE' | 'EXACT_RERUN_NOOP'; audience: Json; targets: Json; destinations: Json[]; non_target: { digest_algorithm: string; digest: string; client_count: number; grant_count: number } };

const TARGETS: readonly Target[] = Object.freeze([
  Object.freeze({ caller: 'svc-forum', principalExternalRef: 'service:v1:principal:svc-forum', principalDisplayName: 'svc-forum service', clientExternalRef: 'service:v1:client:svc-forum:agent-core-notification-ingress-v1', clientId: 'mc_Ez8kTAKKvcf2pF40aoUM4q9M', productionDestination: '/Users/yanfenma/.local/services/svc-forum/notification-ingress.env' }),
  Object.freeze({ caller: 'svc-workflow', principalExternalRef: 'service:v1:principal:svc-workflow', principalDisplayName: 'svc-workflow service', clientExternalRef: 'service:v1:client:svc-workflow:agent-core-notification-ingress-v1', clientId: 'mc_uYu1fDfNHjzUlRQGJdTajz9n', productionDestination: '/Users/yanfenma/.local/services/svc-workflow/.env' }),
]);

class Refusal extends Error { constructor(message: string) { super(message); this.name = 'Refusal'; } }
function refuse(message: string): never { throw new Refusal(message); }
function object(value: unknown, label: string): Record<string, unknown> { if (typeof value !== 'object' || value === null || Array.isArray(value)) refuse(`${label} must be an object`); return value as Record<string, unknown>; }
function exactKeys(value: Record<string, unknown>, keys: readonly string[], label: string): void { const a = Object.keys(value).sort(); const e = [...keys].sort(); if (a.length !== e.length || a.some((v, i) => v !== e[i])) refuse(`${label} has missing or additional fields`); }
function text(value: unknown, label: string, max = 2048): string { if (typeof value !== 'string' || value.length === 0 || Buffer.byteLength(value) > max) refuse(`${label} is invalid`); return value; }
function hex(value: unknown, length: number, label: string): string { const result = text(value, label); if (!new RegExp(`^[0-9a-f]{${length}}$`).test(result)) refuse(`${label} must be lowercase ${length}-hex`); return result; }
function canonical(value: unknown): unknown { if (Array.isArray(value)) return value.map(canonical); if (value !== null && typeof value === 'object') return Object.fromEntries(Object.keys(value as Record<string, unknown>).sort().map((k) => [k, canonical((value as Record<string, unknown>)[k])])); return value; }
function canonicalBytes(value: unknown): Buffer { return Buffer.from(JSON.stringify(canonical(value)), 'utf8'); }
function sha256(value: Buffer | string): string { return createHash('sha256').update(value).digest('hex'); }
function same(a: unknown, b: unknown): boolean { return canonicalBytes(a).equals(canonicalBytes(b)); }
function ascii(a: string, b: string): number { return Buffer.compare(Buffer.from(a), Buffer.from(b)); }
function dateJson(value: unknown): string | null { return value instanceof Date ? value.toISOString() : value === null ? null : String(value); }
function report(operation: string, result: string, planDigest: string | null, classification: string | null, writes: Record<string, number>, nonTarget: string | null, residual: string[] = []): void {
  const value = { schema_version: 1, operation, result, plan_sha256: planDigest, classification, writes, non_target_digest: nonTarget, residual_coordinates: residual };
  exactKeys(value, REPORT_KEYS, 'report'); process.stdout.write(`${JSON.stringify(value)}\n`);
}

// Reject duplicate decoded object keys before JSON.parse (approval/plan/descriptor are authority inputs).
function parseUnique(bytes: Buffer, label: string, limit = 1024 * 1024): Json {
  if (bytes.length === 0 || bytes.length > limit || !Buffer.from(bytes.toString('utf8')).equals(bytes)) refuse(`${label} bytes are invalid`);
  const input = bytes.toString('utf8'); let i = 0;
  const ws = () => { while (/[\x20\x09\x0a\x0d]/.test(input[i] ?? 'x')) i += 1; };
  const str = (): string => { const start = i; if (input[i++] !== '"') refuse(`${label} JSON invalid`); let esc = false; while (i < input.length) { const c = input[i++]; if (c === '\\') { esc = true; i += 1; } else if (c === '"') { try { return JSON.parse(input.slice(start, i)) as string; } catch { refuse(`${label} JSON string invalid`); } } else if (c.charCodeAt(0) < 32) refuse(`${label} JSON string invalid`); } refuse(`${label} JSON unterminated`); };
  const val = (): void => { ws(); const c = input[i]; if (c === '{') { i += 1; ws(); const keys = new Set<string>(); if (input[i] === '}') { i += 1; return; } while (true) { ws(); const k = str(); if (keys.has(k)) refuse(`${label} duplicate member`); keys.add(k); ws(); if (input[i++] !== ':') refuse(`${label} JSON invalid`); val(); ws(); const sep = input[i++]; if (sep === '}') return; if (sep !== ',') refuse(`${label} JSON invalid`); } } if (c === '[') { i += 1; ws(); if (input[i] === ']') { i += 1; return; } while (true) { val(); ws(); const sep = input[i++]; if (sep === ']') return; if (sep !== ',') refuse(`${label} JSON invalid`); } } if (c === '"') { str(); return; } const m = /^(?:true|false|null|-?(?:0|[1-9]\d*)(?:\.\d+)?(?:[eE][+-]?\d+)?)/.exec(input.slice(i)); if (!m) refuse(`${label} JSON invalid`); i += m[0].length; };
  val(); ws(); if (i !== input.length) refuse(`${label} trailing bytes`); try { return JSON.parse(input) as Json; } catch { refuse(`${label} JSON invalid`); }
}
function readFifo(fdValue: string | undefined, label: string): Json { if (!fdValue || !/^(?:[3-9]|[1-9]\d+)$/.test(fdValue)) refuse(`${label} descriptor invalid`); const fd = Number(fdValue); if (!fstatSync(fd).isFIFO()) refuse(`${label} must be a FIFO`); const chunks: Buffer[] = []; let total = 0; while (true) { const b = Buffer.allocUnsafe(65536); const n = readSync(fd, b, 0, b.length, null); if (n === 0) break; total += n; if (total > 1024 * 1024) { closeSync(fd); refuse(`${label} too large`); } chunks.push(b.subarray(0, n)); } closeSync(fd); return parseUnique(Buffer.concat(chunks), label); }

function repoCoordinates(requireClean: boolean): { implementation: string; specRevision: string } {
  const git = '/usr/bin/git'; const top = execFileSync(git, ['-C', ROOT, 'rev-parse', '--show-toplevel'], { encoding: 'utf8' }).trim(); if (`${top}/` !== ROOT) refuse('repository root mismatch');
  if (requireClean && execFileSync(git, ['-C', ROOT, 'status', '--porcelain', '--untracked-files=all'], { encoding: 'utf8' }) !== '') refuse('production apply requires a clean worktree');
  const implementation = hex(execFileSync(git, ['-C', ROOT, 'rev-parse', 'HEAD'], { encoding: 'utf8' }).trim(), 40, 'HEAD');
  const specRevision = hex(execFileSync(git, ['-C', ROOT, 'rev-parse', `HEAD:${SPEC_PATH}`], { encoding: 'utf8' }).trim(), 40, 'Spec blob');
  const spec = readFileSync(resolve(ROOT, SPEC_PATH), 'utf8');
  if (!spec.startsWith('---\n') || !spec.includes(`spec_id: ${SPEC_ID}`) || !spec.includes('status: accepted') || !spec.includes('implementation_authority: contracts') || !spec.includes('production_apply_authority: none')) refuse('governing Spec lifecycle/authority mismatch');
  return { implementation, specRevision };
}

function parseEnv(bytes: Buffer): Map<string, string> { const result = new Map<string, string>(); for (const line of bytes.toString('utf8').split(/\r?\n/)) { if (line === '' || /^\s*#/.test(line)) continue; const m = /^([A-Z][A-Z0-9_]*)=(.*)$/.exec(line); if (!m || result.has(m[1])) refuse('destination has malformed or duplicate environment keys'); result.set(m[1], m[2]); } return result; }
function lstatMaybe(path: string): Stats | null { try { return lstatSync(path); } catch (error) { if (typeof error === 'object' && error !== null && 'code' in error && error.code === 'ENOENT') return null; throw error; } }
function rejectSymlinkParents(path: string): void { let current = dirname(path); while (true) { const st = lstatMaybe(current); if (st && (!st.isDirectory() || st.isSymbolicLink())) refuse('destination parent chain must contain only real directories'); const parent = dirname(current); if (parent === current) break; current = parent; } }
function destination(path: string, expectedUid: number, target: Target): Destination {
  if (!path.startsWith('/') || path.includes('\0')) refuse('destination must be absolute'); rejectSymlinkParents(path);
  const st = lstatMaybe(path); if (st === null) return { path, exists: false, mode: null, uid: null, keys: [], exact: false, secret: null, bytes: null };
  if (!st.isFile() || st.isSymbolicLink() || st.nlink !== 1) refuse('destination must be one regular non-linked file');
  const bytes = readFileSync(path); const env = parseEnv(bytes); const client = env.get('AUTH_NOTIFICATION_INGRESS_CLIENT_ID') ?? null; const secret = env.get('AUTH_NOTIFICATION_INGRESS_CLIENT_SECRET') ?? null;
  const exact = (st.mode & 0o777) === 0o600 && st.uid === expectedUid && client === target.clientId && typeof secret === 'string' && secret.length > 0;
  return { path, exists: true, mode: st.mode & 0o777, uid: st.uid, keys: [...env.keys()].sort(ascii), exact, secret, bytes };
}
function safeDestination(d: Destination): Json { return { path: d.path, exists: d.exists, mode: d.mode, uid: d.uid, keys_present: d.keys, exact_metadata_and_keys: d.exact }; }
function destinationBytes(pre: Destination, target: Target, secret: string): Buffer { const env = pre.bytes ? parseEnv(pre.bytes) : new Map<string, string>(); env.set('AUTH_NOTIFICATION_INGRESS_CLIENT_ID', target.clientId); env.set('AUTH_NOTIFICATION_INGRESS_CLIENT_SECRET', secret); return Buffer.from([...env.entries()].sort(([a], [b]) => ascii(a, b)).map(([k, v]) => `${k}=${v}\n`).join(''), 'utf8'); }
function stageFile(path: string, bytes: Buffer): string { rejectSymlinkParents(path); const parent = lstatSync(dirname(path)); if (!parent.isDirectory() || parent.isSymbolicLink() || (parent.mode & 0o022) !== 0) refuse('destination parent must be an existing non-group/world-writable real directory'); const temp = `${path}.nsc-stage-${randomUUID()}`; const fd = openSync(temp, 'wx', 0o600); try { fchmodSync(fd, 0o600); writeSync(fd, bytes); fsyncSync(fd); } finally { closeSync(fd); } return temp; }
function syncDirectory(path: string): void { const fd = openSync(dirname(path), 'r'); try { fsyncSync(fd); } finally { closeSync(fd); } }
function restoreDestination(pre: Destination): void { if (pre.bytes === null) { if (existsSync(pre.path)) unlinkSync(pre.path); syncDirectory(pre.path); return; } const temp = stageFile(pre.path, pre.bytes); chmodSync(temp, pre.mode ?? 0o600); renameSync(temp, pre.path); syncDirectory(pre.path); }
function durableMarker(ctx: Context, result: 'ROLLBACK_INCOMPLETE' | 'OUTCOME_UNKNOWN', residual: string[], planDigest: string): void { const marker = { schema_version: 1, result, spec_id: SPEC_ID, plan_sha256: planDigest, environment: ctx.environment, residual_coordinates: residual.sort(ascii) }; mkdirSync(dirname(ctx.markerPath), { recursive: true, mode: 0o700 }); const temp = stageFile(ctx.markerPath, Buffer.from(`${JSON.stringify(marker)}\n`)); renameSync(temp, ctx.markerPath); syncDirectory(ctx.markerPath); }
function clearMarker(ctx: Context): void { if (existsSync(ctx.markerPath)) { unlinkSync(ctx.markerPath); syncDirectory(ctx.markerPath); } }

function hashSecret(secret: string): string { const salt = randomBytes(16).toString('hex'); return `${salt}:${scryptSync(secret, salt, 64, { N: 16384, r: 8, p: 1 }).toString('hex')}`; }
function verifySecret(secret: string, stored: string): boolean { const m = /^([0-9a-f]{32}):([0-9a-f]{128})$/.exec(stored); if (!m) return false; const actual = scryptSync(secret, m[1], 64, { N: 16384, r: 8, p: 1 }); const expected = Buffer.from(m[2], 'hex'); return actual.length === expected.length && timingSafeEqual(actual, expected); }
function safeAfter(target: Target, principalId: string): Prisma.InputJsonObject { return { client_id: target.clientId, client_kind: 'machine', principal_id: principalId, principal_type: 'service', human_audience_grants: [], machine_access_grants: { [AUDIENCE_ID]: [SCOPE] }, delegation_grants: {}, status: 'active', version: 1 }; }

async function audienceProjection(db: Db): Promise<Json> { const rows = await db.authAudience.findMany({ where: { audienceId: AUDIENCE_ID } }); if (rows.length !== 1) refuse('Audience absent or duplicate'); const a = rows[0]; const exact = a.resourceService === AUDIENCE_ID && a.scopeNamespace === 'notification' && same(a.acceptedPrincipalTypes, ['service']) && same(a.registeredScopes, [SCOPE]) && !a.humanAccessEnabled && a.machineAccessEnabled && !a.delegatedAccessEnabled && a.status === 'active' && a.freezeReady;
  if (!exact) refuse('Audience mismatch'); return { audience_id: a.audienceId, resource_service: a.resourceService, scope_namespace: a.scopeNamespace, accepted_principal_types: a.acceptedPrincipalTypes, registered_scopes: a.registeredScopes, human_access_enabled: a.humanAccessEnabled, machine_access_enabled: a.machineAccessEnabled, delegated_access_enabled: a.delegatedAccessEnabled, status: a.status, freeze_ready: a.freezeReady, version: a.version, created_at: a.createdAt.toISOString(), updated_at: a.updatedAt.toISOString() }; }

async function targetState(db: Db, destinations: Destination[], coordinates: { implementation: string; specRevision: string }, planDigestForAudit?: string, approval?: Approval): Promise<TargetState> {
  const safe: Json[] = []; const internalIds: Record<string, string> = {}; const secretHashes: Record<string, string> = {}; const auditsSafe: Json[] = []; let absent = 0; let exact = 0;
  for (const [index, target] of TARGETS.entries()) {
    const principals = await db.machinePrincipal.findMany({ where: { externalRef: target.principalExternalRef } });
    const clients = await db.machineClient.findMany({ where: { OR: [{ externalRef: target.clientExternalRef }, { clientId: target.clientId }] }, include: { accessGrants: true, trustedProxy: { include: { delegationGrants: true } } } });
    const audits = await db.grantChangeAudit.findMany({ where: { clientId: target.clientId }, orderBy: [{ timestamp: 'asc' }, { id: 'asc' }] });
    if (principals.length === 0 && clients.length === 0 && audits.length === 0 && !destinations[index].exists) { absent += 1; safe.push({ caller: target.caller, state: 'ABSENT', desired: { principal: { principal_type: 'service', agent_id: null, owner_user_id: null, external_ref: target.principalExternalRef, display_name: target.principalDisplayName, status: 'active', disabled_at: null }, client: { client_id: target.clientId, external_ref: target.clientExternalRef, principal_external_ref: target.principalExternalRef, status: 'active', allowed_resources: [], allowed_scopes: [], rotated_at: null, revoked_at: null }, grant: { audience_id: AUDIENCE_ID, scopes: [SCOPE], version: 1 }, destination: { path: destinations[index].path, owner: 'yanfenma', mode: 0o600, keys_present: ['AUTH_NOTIFICATION_INGRESS_CLIENT_ID', 'AUTH_NOTIFICATION_INGRESS_CLIENT_SECRET'] } } }); continue; }
    if (principals.length !== 1 || clients.length !== 1 || audits.length !== 1) refuse(`${target.caller} target is partial, duplicate, ambiguous, or audit-mismatched`);
    const p = principals[0]; const c = clients[0]; const g = c.accessGrants;
    const shape = p.externalRef === target.principalExternalRef && p.principalType === 'service' && p.agentId === null && p.ownerUserId === null && p.displayName === target.principalDisplayName && p.status === 'active' && p.disabledAt === null && c.externalRef === target.clientExternalRef && c.clientId === target.clientId && c.machinePrincipalId === p.id && c.status === 'active' && c.allowedResources.length === 0 && c.allowedScopes.length === 0 && c.rotatedAt === null && c.revokedAt === null && c.trustedProxy === null && g.length === 1 && g[0].audienceId === AUDIENCE_ID && same(g[0].scopes, [SCOPE]) && g[0].version === 1 && destinations[index].exact && destinations[index].secret !== null && verifySecret(destinations[index].secret!, c.secretHash);
    const after = safeAfter(target, p.id); const audit = audits[0]; const reasonExpected = planDigestForAudit && approval ? `spec_blob=${coordinates.specRevision};plan_sha256=${planDigestForAudit};environment=${approval.environment}` : null;
    const closedReason = new RegExp(`^spec_blob=${coordinates.specRevision};plan_sha256=[0-9a-f]{64};environment=[a-z0-9][a-z0-9._-]{0,63}$`).test(audit.reason);
    const auditShape = audit.migrationId === MIGRATION_ID && audit.sourceGitCommit === coordinates.implementation && audit.clientId === target.clientId && audit.changeType === 'create' && audit.expectedGrantVersion === null && audit.resultingGrantVersion === 1 && audit.beforeValue === null && same(audit.afterValue, after) && audit.operatorId.length > 0 && audit.approvalRef.length > 0 && closedReason && (reasonExpected === null || (audit.reason === reasonExpected && audit.operatorId === approval!.operator_id && audit.approvalRef === approval!.approval_ref));
    if (!shape || !auditShape) refuse(`${target.caller} target has SHAPE_MISMATCH, DESTINATION_MISMATCH, or AUDIT_MISMATCH`);
    exact += 1; internalIds[target.caller] = c.id; secretHashes[target.caller] = c.secretHash;
    const safeAudit = { change_id: audit.id, migration_id: audit.migrationId, source_git_commit: audit.sourceGitCommit, operator_id: audit.operatorId, approval_ref: audit.approvalRef, reason: audit.reason, client_id: audit.clientId, change_type: audit.changeType, expected_grant_version: audit.expectedGrantVersion, resulting_grant_version: audit.resultingGrantVersion, before_value: audit.beforeValue as Json, after_value: audit.afterValue as Json, timestamp: audit.timestamp.toISOString() }; exactKeys(safeAudit, AUDIT_KEYS, 'audit envelope'); auditsSafe.push(safeAudit);
    safe.push({ caller: target.caller, state: 'EXACT', principal: { id: p.id, principal_type: p.principalType, external_ref: p.externalRef, display_name: p.displayName, status: p.status }, client: { id: c.id, client_id: c.clientId, external_ref: c.externalRef, machine_principal_id: c.machinePrincipalId, status: c.status, allowed_resources: c.allowedResources, allowed_scopes: c.allowedScopes }, grant: { audience_id: g[0].audienceId, scopes: g[0].scopes, version: g[0].version }, secret_to_hash_match: true, audit: safeAudit });
  }
  if (absent === TARGETS.length) return { classification: 'ABSENT', safe, internalIds, secretHashes, audits: auditsSafe };
  if (exact === TARGETS.length) return { classification: 'EXACT_RERUN_NOOP', safe, internalIds, secretHashes, audits: auditsSafe };
  refuse('mixed target state is PARTIAL');
}

type RawClient = { id: string; client_id: string; machine_principal_id: string; secret_hash: string; external_ref: string | null; status: string; allowed_resources: string[]; allowed_scopes: string[]; created_at: Date; updated_at: Date; rotated_at: Date | null; revoked_at: Date | null };
type RawGrant = { machine_client_id: string; audience_id: string; scopes: string[]; version: number; created_at: Date; updated_at: Date };
function framed(rows: Array<{ kind: string; ordinal: string; fields: unknown[] }>): string { const hash = createHash('sha256'); for (const row of rows.sort((a, b) => ascii(`${a.kind}\0${a.ordinal}`, `${b.kind}\0${b.ordinal}`))) { for (const field of [row.kind, row.ordinal, ...row.fields]) { const bytes = canonicalBytes(field); hash.update(Buffer.from(`${bytes.length}:`, 'ascii')); hash.update(bytes); hash.update(Buffer.from(',', 'ascii')); } } return hash.digest('hex'); }
async function nonTarget(db: Db): Promise<{ digest: string; clients: number; grants: number }> {
  const clients = await db.$queryRaw<RawClient[]>(Prisma.sql`SELECT id, client_id, machine_principal_id, secret_hash, external_ref, status, allowed_resources, allowed_scopes, created_at, updated_at, rotated_at, revoked_at FROM machine_clients WHERE client_id NOT IN (${Prisma.join(TARGETS.map((t) => t.clientId))}) AND (external_ref IS NULL OR external_ref NOT IN (${Prisma.join(TARGETS.map((t) => t.clientExternalRef))})) ORDER BY id`);
  const targetIds = await db.$queryRaw<Array<{ id: string }>>(Prisma.sql`SELECT id FROM machine_clients WHERE client_id IN (${Prisma.join(TARGETS.map((t) => t.clientId))}) OR external_ref IN (${Prisma.join(TARGETS.map((t) => t.clientExternalRef))})`);
  const grants = targetIds.length === 0 ? await db.$queryRaw<RawGrant[]>`SELECT machine_client_id, audience_id, scopes, version, created_at, updated_at FROM machine_access_grants ORDER BY machine_client_id, audience_id` : await db.$queryRaw<RawGrant[]>(Prisma.sql`SELECT machine_client_id, audience_id, scopes, version, created_at, updated_at FROM machine_access_grants WHERE machine_client_id NOT IN (${Prisma.join(targetIds.map((r) => Prisma.sql`${r.id}::uuid`))}) ORDER BY machine_client_id, audience_id`);
  const rows: Array<{ kind: string; ordinal: string; fields: unknown[] }> = clients.map((c) => ({ kind: 'machine_client', ordinal: c.id, fields: [c.id, c.client_id, c.machine_principal_id, sha256(c.secret_hash), c.external_ref, c.status, c.allowed_resources, c.allowed_scopes, dateJson(c.created_at), dateJson(c.updated_at), dateJson(c.rotated_at), dateJson(c.revoked_at)] }));
  rows.push(...grants.map((g) => ({ kind: 'machine_access_grant', ordinal: `${g.machine_client_id}\0${g.audience_id}`, fields: [g.machine_client_id, g.audience_id, g.scopes, g.version, dateJson(g.created_at), dateJson(g.updated_at)] })));
  return { digest: framed(rows), clients: clients.length, grants: grants.length };
}

async function loadLive(db: Db, ctx: Context, coordinates: { implementation: string; specRevision: string }, planDigestForAudit?: string, approval?: Approval): Promise<Live> { const identities = await db.$queryRaw<Array<{ database: string; address: string; port: number }>>`SELECT current_database()::text AS database, COALESCE(inet_server_addr()::text, 'local') AS address, inet_server_port()::integer AS port`; if (identities.length !== 1 || !identities[0].database || !identities[0].address || !Number.isInteger(identities[0].port)) refuse('database environment identity unavailable'); const databaseIdentity = identities[0]; const audience = await audienceProjection(db); const destinationRuntime = TARGETS.map((t) => destination(ctx.destinations[t.caller], ctx.expectedUid, t)); const targets = await targetState(db, destinationRuntime, coordinates, planDigestForAudit, approval); const nt = await nonTarget(db); return { databaseIdentity, audience, targets, destinations: destinationRuntime.map(safeDestination), destinationRuntime, nonTargetDigest: nt.digest, nonTargetCounts: { clients: nt.clients, grants: nt.grants } }; }
function buildPlan(live: Live, ctx: Context, coordinates: { implementation: string; specRevision: string }): Plan { return { plan_version: PLAN_VERSION, spec_id: SPEC_ID, spec_revision: coordinates.specRevision, implementation_commit: coordinates.implementation, environment: ctx.environment, database_identity: live.databaseIdentity, classification: live.targets.classification === 'ABSENT' ? 'CREATE' : 'EXACT_RERUN_NOOP', audience: live.audience, targets: live.targets.safe, destinations: live.destinations, non_target: { digest_algorithm: 'SHA-256-length-delimited-v1', digest: live.nonTargetDigest, client_count: live.nonTargetCounts.clients, grant_count: live.nonTargetCounts.grants } }; }
function planEnvelope(plan: Plan): { plan: Plan; plan_sha256: string } { return { plan, plan_sha256: sha256(canonicalBytes(plan)) }; }
function readPlan(path: string, expectedDigest: string, ctx: Context, coordinates: { implementation: string; specRevision: string }): { plan: Plan; digest: string } { const parsed = object(parseUnique(readFileSync(path), 'plan'), 'plan envelope'); exactKeys(parsed, ['plan', 'plan_sha256'], 'plan envelope'); const plan = object(parsed.plan, 'plan') as unknown as Plan; const digest = hex(parsed.plan_sha256, 64, 'plan_sha256'); if (digest !== expectedDigest || sha256(canonicalBytes(plan)) !== digest) refuse('approved plan digest mismatch'); if (plan.plan_version !== PLAN_VERSION || plan.spec_id !== SPEC_ID || plan.spec_revision !== coordinates.specRevision || plan.implementation_commit !== coordinates.implementation || plan.environment !== ctx.environment) refuse('approved plan is stale or wrong-environment'); return { plan, digest }; }

function approval(value: Json, planDigest: string, ctx: Context, coordinates: { implementation: string; specRevision: string }): Approval { const v = object(value, 'approval'); const keys = ['spec_id', 'spec_revision', 'implementation_commit', 'plan_sha256', 'environment', 'window_not_before', 'window_not_after', 'operator_id', 'approval_ref']; exactKeys(v, keys, 'approval'); const result = Object.fromEntries(keys.map((k) => [k, text(v[k], `approval.${k}`)])) as Approval; if (result.spec_id !== SPEC_ID || result.spec_revision !== coordinates.specRevision || result.implementation_commit !== coordinates.implementation || result.plan_sha256 !== planDigest || result.environment !== ctx.environment) refuse('approval binding mismatch'); const before = Date.parse(result.window_not_before); const after = Date.parse(result.window_not_after); const now = Date.now(); if (!Number.isFinite(before) || !Number.isFinite(after) || now < before || now > after || after - before > 4 * 60 * 60 * 1000) refuse('approval execution window invalid'); if (!/^[A-Za-z0-9][A-Za-z0-9._:@/-]{0,127}$/.test(result.operator_id)) refuse('approval operator_id invalid'); const approvalRefOk = ctx.conformance ? /^conformance:\/\/owner-approval\/[a-z0-9-]+$/.test(result.approval_ref) : /^https:\/\/github\.com\/mayf3\/auth-service\/(?:issues|pull)\/[1-9][0-9]*(?:#(?:issuecomment|discussion_r)[-0-9]+)?$/.test(result.approval_ref); if (!approvalRefOk) refuse('approval_ref is not an allowed immutable review coordinate'); return result; }

async function createRows(tx: Prisma.TransactionClient, secrets: string[], hashes: string[], auth: Approval, coordinates: { implementation: string; specRevision: string }, planDigest: string): Promise<void> { for (const [i, target] of TARGETS.entries()) { const p = await tx.machinePrincipal.create({ data: { principalType: 'service', agentId: null, ownerUserId: null, displayName: target.principalDisplayName, externalRef: target.principalExternalRef, requestDigest: null, status: 'active' } }); await tx.machineClient.create({ data: { clientId: target.clientId, machinePrincipalId: p.id, secretHash: hashes[i], externalRef: target.clientExternalRef, status: 'active', allowedResources: [], allowedScopes: [] } }); await tx.machineAccessGrant.create({ data: { machineClient: { connect: { clientId: target.clientId } }, audience: { connect: { audienceId: AUDIENCE_ID } }, scopes: [SCOPE], version: 1 } }); const id = randomUUID(); const timestamp = new Date(); const after = safeAfter(target, p.id); const envelope = { change_id: id, migration_id: MIGRATION_ID, source_git_commit: coordinates.implementation, operator_id: auth.operator_id, approval_ref: auth.approval_ref, reason: `spec_blob=${coordinates.specRevision};plan_sha256=${planDigest};environment=${auth.environment}`, client_id: target.clientId, change_type: 'create', expected_grant_version: null, resulting_grant_version: 1, before_value: null, after_value: after, timestamp: timestamp.toISOString() }; exactKeys(envelope, AUDIT_KEYS, 'audit envelope'); await tx.grantChangeAudit.create({ data: { id, migrationId: MIGRATION_ID, sourceGitCommit: coordinates.implementation, operatorId: auth.operator_id, approvalRef: auth.approval_ref, reason: envelope.reason, clientId: target.clientId, changeType: 'create', expectedGrantVersion: null, resultingGrantVersion: 1, beforeValue: Prisma.DbNull, afterValue: after, timestamp } }); } }

async function apply(prisma: PrismaClient, ctx: Context, approved: { plan: Plan; digest: string }, auth: Approval, coordinates: { implementation: string; specRevision: string }): Promise<void> {
  if (existsSync(ctx.markerPath)) refuse('durable recovery marker blocks APPLY');
  const preliminary = await loadLive(prisma, ctx, coordinates); const currentPlan = buildPlan(preliminary, ctx, coordinates); if (!same(currentPlan, approved.plan)) refuse('plan-to-live drift');
  if (approved.plan.classification === 'EXACT_RERUN_NOOP') {
    const lockedDigest = await prisma.$transaction(async (tx) => {
      await tx.$executeRawUnsafe('LOCK TABLE auth_audiences IN SHARE MODE'); await tx.$executeRawUnsafe('LOCK TABLE machine_principals IN SHARE ROW EXCLUSIVE MODE'); await tx.$executeRawUnsafe('LOCK TABLE machine_clients IN SHARE ROW EXCLUSIVE MODE'); await tx.$executeRawUnsafe('LOCK TABLE machine_access_grants IN SHARE ROW EXCLUSIVE MODE'); await tx.$executeRawUnsafe('LOCK TABLE grant_change_audits IN SHARE ROW EXCLUSIVE MODE'); await tx.$executeRaw`SELECT pg_advisory_xact_lock(${GLOBAL_LOCK})`;
      const locked = await loadLive(tx, ctx, coordinates); if (!same(buildPlan(locked, ctx, coordinates), approved.plan)) refuse('NOOP plan-to-live drift inside serializable transaction');
      return locked.nonTargetDigest;
    }, { isolationLevel: Prisma.TransactionIsolationLevel.Serializable, timeout: 60_000, maxWait: 10_000 });
    report('apply', 'NOOP', approved.digest, 'EXACT_RERUN_NOOP', { principals: 0, clients: 0, grants: 0, audits: 0, destinations: 0, secrets_generated: 0 }, lockedDigest); return;
  }
  const pre = preliminary.destinationRuntime; const staged: string[] = []; const installed: Destination[] = []; let mutationStarted = false; let callbackComplete = false; let transactionCommitted = false;
  const secretValues: string[] = []; const hashes: string[] = [];
  try {
    await prisma.$transaction(async (tx) => {
      await tx.$executeRawUnsafe('LOCK TABLE auth_audiences IN SHARE MODE'); await tx.$executeRawUnsafe('LOCK TABLE machine_principals IN SHARE ROW EXCLUSIVE MODE'); await tx.$executeRawUnsafe('LOCK TABLE machine_clients IN SHARE ROW EXCLUSIVE MODE'); await tx.$executeRawUnsafe('LOCK TABLE machine_access_grants IN SHARE ROW EXCLUSIVE MODE'); await tx.$executeRawUnsafe('LOCK TABLE grant_change_audits IN SHARE ROW EXCLUSIVE MODE'); await tx.$executeRaw`SELECT pg_advisory_xact_lock(${GLOBAL_LOCK})`;
      const locked = await loadLive(tx, ctx, coordinates); const lockedPlan = buildPlan(locked, ctx, coordinates); if (!same(lockedPlan, approved.plan)) refuse('plan-to-live drift inside serializable transaction'); if (locked.nonTargetDigest !== approved.plan.non_target.digest) refuse('non-target digest changed before mutation');
      durableMarker(ctx, 'OUTCOME_UNKNOWN', ['apply_in_progress'], approved.digest); mutationStarted = true; secretValues.push(randomBytes(32).toString('base64url'), randomBytes(32).toString('base64url')); hashes.push(...secretValues.map(hashSecret));
      for (const [i, target] of TARGETS.entries()) staged.push(stageFile(pre[i].path, destinationBytes(pre[i], target, secretValues[i])));
      await createRows(tx, secretValues, hashes, auth, coordinates, approved.digest);
      const precommitDigest = await nonTarget(tx); if (precommitDigest.digest !== approved.plan.non_target.digest) refuse('non-target digest changed before commit');
      for (const [i, stagedPath] of staged.entries()) { rejectSymlinkParents(pre[i].path); if (lstatMaybe(pre[i].path) !== null) refuse('concurrent destination drift before install'); renameSync(stagedPath, pre[i].path); installed.push(pre[i]); syncDirectory(pre[i].path); }
      if (ctx.faultInjection === 'after-install-and-restore-fail') refuse('conformance injected post-install failure');
      const after = await loadLive(tx, ctx, coordinates, approved.digest, auth); if (after.targets.classification !== 'EXACT_RERUN_NOOP' || after.nonTargetDigest !== approved.plan.non_target.digest) refuse('precommit complete projection verification failed'); callbackComplete = true;
    }, { isolationLevel: Prisma.TransactionIsolationLevel.Serializable, timeout: 60_000, maxWait: 10_000 }); transactionCommitted = true;
    const verified = await loadLive(prisma, ctx, coordinates, approved.digest, auth); if (verified.nonTargetDigest !== approved.plan.non_target.digest) { durableMarker(ctx, 'ROLLBACK_INCOMPLETE', ['non_target_digest_after_commit'], approved.digest); report('apply', 'ROLLBACK_INCOMPLETE', approved.digest, 'CREATE', { principals: 2, clients: 2, grants: 2, audits: 2, destinations: 2, secrets_generated: secretValues.length }, verified.nonTargetDigest, ['non_target_digest_after_commit']); process.exitCode = 40; return; }
    clearMarker(ctx); report('apply', 'COMMITTED', approved.digest, 'CREATE', { principals: 2, clients: 2, grants: 2, audits: 2, destinations: 2, secrets_generated: secretValues.length }, verified.nonTargetDigest);
  } catch (error) {
    for (const path of staged) if (existsSync(path)) { try { unlinkSync(path); } catch { /* included in rollback verification */ } }
    const unknown = transactionCommitted || (callbackComplete && !(error instanceof Refusal)); const residual: string[] = unknown ? ['database_commit_outcome'] : [];
    if (!unknown) {
      for (const d of installed.reverse()) { try { if (ctx.faultInjection === 'after-install-and-restore-fail') throw new Error('conformance injected restore failure'); restoreDestination(d); } catch { residual.push(`destination:${d.path}`); } }
      try { const restored = await loadLive(prisma, ctx, coordinates); if (!same(buildPlan(restored, ctx, coordinates), approved.plan) || restored.nonTargetDigest !== approved.plan.non_target.digest) residual.push('database_or_projection_prestate'); } catch { residual.push('rollback_verification'); }
    }
    if (unknown || residual.length > 0) { const result = unknown ? 'OUTCOME_UNKNOWN' : 'ROLLBACK_INCOMPLETE'; durableMarker(ctx, result, residual, approved.digest); report('apply', result, approved.digest, 'CREATE', { principals: 0, clients: 0, grants: 0, audits: 0, destinations: 0, secrets_generated: secretValues.length }, approved.plan.non_target.digest, residual); process.exitCode = unknown ? 41 : 40; return; }
    if (mutationStarted) { try { clearMarker(ctx); } catch { durableMarker(ctx, 'ROLLBACK_INCOMPLETE', ['recovery_marker_clear'], approved.digest); report('apply', 'ROLLBACK_INCOMPLETE', approved.digest, 'CREATE', { principals: 0, clients: 0, grants: 0, audits: 0, destinations: 0, secrets_generated: secretValues.length }, approved.plan.non_target.digest, ['recovery_marker_clear']); process.exitCode = 40; return; } const safeError = error instanceof Refusal ? error.message : (typeof error === 'object' && error !== null && 'code' in error && typeof error.code === 'string' ? `database:${error.code}` : 'operator:unclassified'); process.stderr.write(`${JSON.stringify({ schema_version: 1, result: 'ROLLED_BACK', error: safeError })}\n`); report('apply', 'ROLLED_BACK', approved.digest, 'CREATE', { principals: 0, clients: 0, grants: 0, audits: 0, destinations: 0, secrets_generated: secretValues.length }, approved.plan.non_target.digest); process.exitCode = 30; return; }
    clearMarker(ctx); throw error;
  } finally { secretValues.fill(''); hashes.fill(''); }
}

function descriptor(value: Json): Context {
  const v = object(value, 'conformance descriptor'); exactKeys(v, ['schema_version', 'container_id', 'nonce', 'database_url', 'environment', 'destination_root', 'expected_uid', 'marker_path', 'fault_injection'], 'conformance descriptor'); if (v.schema_version !== 1 || v.environment !== 'disposable-conformance' || (v.fault_injection !== 'none' && v.fault_injection !== 'after-install-and-restore-fail')) refuse('conformance descriptor mismatch');
  const containerId = hex(v.container_id, 64, 'container_id'); const nonce = hex(v.nonce, 64, 'nonce'); const url = text(v.database_url, 'database_url'); const parsed = new URL(url); if (parsed.protocol !== 'postgresql:' || parsed.hostname !== '127.0.0.1' || parsed.pathname !== '/auth_nsc_conformance') refuse('conformance database is not disposable-loopback');
  const inspected = parseUnique(Buffer.from(execFileSync('/usr/local/bin/docker', ['inspect', containerId], { env: { PATH: '/usr/local/bin:/usr/bin:/bin' } })), 'docker inspect', 2 * 1024 * 1024); if (!Array.isArray(inspected) || inspected.length !== 1) refuse('conformance container identity invalid'); const info = object(inspected[0], 'docker inspect entry'); const config = object(info.Config, 'docker Config'); const state = object(info.State, 'docker State'); const host = object(info.HostConfig, 'docker HostConfig'); const network = object(info.NetworkSettings, 'docker NetworkSettings'); const labels = object(config.Labels, 'docker labels'); const ports = object(network.Ports, 'docker ports'); const binding = ports['5432/tcp'];
  if (config.Image !== 'postgres@sha256:57c72fd2a128e416c7fcc499958864df5301e940bca0a56f58fddf30ffc07777' || state.Running !== true || labels['com.mayf3.auth.nsc-conformance'] !== `sha256:${sha256(nonce)}` || host.NetworkMode !== 'bridge' || host.Privileged !== false || !object(host.Tmpfs, 'docker tmpfs')['/var/lib/postgresql/data'] || !Array.isArray(info.Mounts) || info.Mounts.length !== 0 || !Array.isArray(binding) || binding.length !== 1 || object(binding[0], 'docker port binding').HostIp !== '127.0.0.1' || Number(object(binding[0], 'docker port binding').HostPort) !== Number(parsed.port)) refuse('conformance container is not exact disposable PostgreSQL');
  const declaredRoot = resolve(text(v.destination_root, 'destination_root')); const root = realpathSync(declaredRoot); const rootStat = lstatSync(root); if ((!root.startsWith('/tmp/') && !root.startsWith('/private/tmp/')) || !rootStat.isDirectory() || rootStat.isSymbolicLink() || rootStat.nlink < 1) refuse('conformance destination must be an owned temporary directory'); const expectedUid = v.expected_uid; if (!Number.isInteger(expectedUid) || (expectedUid as number) < 0 || rootStat.uid !== expectedUid || (rootStat.mode & 0o777) !== 0o700) refuse('expected_uid or temporary root ownership/mode invalid'); const declaredMarker = resolve(text(v.marker_path, 'marker_path')); if (!declaredMarker.startsWith(`${declaredRoot}/`)) refuse('marker must be under temporary destination root'); const markerPath = resolve(root, declaredMarker.slice(declaredRoot.length + 1)); return { url, environment: 'disposable-conformance', destinations: { 'svc-forum': resolve(root, 'svc-forum/notification-ingress.env'), 'svc-workflow': resolve(root, 'svc-workflow/.env') }, expectedUid: expectedUid as number, markerPath, conformance: true, faultInjection: v.fault_injection };
}
function productionContext(): Context { const environment = text(process.env.AUTH_NOTIFICATION_INGRESS_ENVIRONMENT, 'AUTH_NOTIFICATION_INGRESS_ENVIRONMENT'); if (!/^[a-z0-9][a-z0-9._-]{0,63}$/.test(environment) || environment === 'disposable-conformance') refuse('production environment coordinate invalid'); const url = text(process.env.DATABASE_URL, 'DATABASE_URL'); const expectedUid = Number(execFileSync('/usr/bin/id', ['-u', 'yanfenma'], { encoding: 'utf8' }).trim()); if (!Number.isSafeInteger(expectedUid) || expectedUid < 0) refuse('yanfenma owner identity cannot be resolved'); return { url, environment, destinations: Object.fromEntries(TARGETS.map((t) => [t.caller, t.productionDestination])), expectedUid, markerPath: '/Users/yanfenma/.local/state/auth-service/notification-ingress-phase-b-recovery-v1.json', conformance: false, faultInjection: 'none' }; }
function args(argv: string[]): Record<string, string | true> { const result: Record<string, string | true> = {}; const valued = new Set(['--plan-file', '--plan-sha256', '--approval-fd', '--descriptor-fd', '--conformance-mode']); for (let i = 0; i < argv.length; i += 1) { const key = argv[i]; if (!key.startsWith('--') || Object.hasOwn(result, key)) refuse(`unknown or duplicate argument ${key}`); if (valued.has(key)) { const value = argv[++i]; if (!value || value.startsWith('--')) refuse(`${key} requires value`); result[key] = value; } else if (['--plan', '--apply', '--verify', '--conformance'].includes(key)) result[key] = true; else refuse(`unknown argument ${key}`); } return result; }

async function main(): Promise<void> {
  const a = args(process.argv.slice(2)); const conformanceMode = a['--conformance'] === true; let ctx: Context; let operation: 'plan' | 'apply' | 'verify';
  if (conformanceMode) { if (process.env.DATABASE_URL !== undefined || Object.keys(a).some((k) => !['--conformance', '--descriptor-fd', '--conformance-mode', '--plan-file', '--plan-sha256', '--approval-fd'].includes(k))) refuse('conformance seam contamination'); ctx = descriptor(readFifo(a['--descriptor-fd'] as string | undefined, 'conformance descriptor')); const mode = a['--conformance-mode'] ?? 'plan'; if (!['plan', 'apply', 'verify'].includes(String(mode))) refuse('conformance mode invalid'); operation = mode as typeof operation; }
  else { const selected = ['--plan', '--apply', '--verify'].filter((k) => a[k] === true); if (selected.length > 1) refuse('modes are mutually exclusive'); operation = selected[0] === '--apply' ? 'apply' : selected[0] === '--verify' ? 'verify' : 'plan'; ctx = productionContext(); }
  const common = conformanceMode ? ['--conformance', '--descriptor-fd', '--conformance-mode'] : []; const modeAllowed = operation === 'plan' ? (conformanceMode ? common : ['--plan']) : operation === 'verify' ? [...common, ...(conformanceMode ? [] : ['--verify']), '--plan-file', '--plan-sha256'] : [...common, ...(conformanceMode ? [] : ['--apply']), '--plan-file', '--plan-sha256', '--approval-fd']; if (Object.keys(a).some((key) => !modeAllowed.includes(key))) refuse(`${operation} received a mode-incompatible argument`);
  const coordinates = repoCoordinates(operation === 'apply' && !conformanceMode); const prisma = new PrismaClient({ datasources: { db: { url: ctx.url } } });
  try {
    if (operation === 'plan') { const live = await loadLive(prisma, ctx, coordinates); const envelope = planEnvelope(buildPlan(live, ctx, coordinates)); process.stdout.write(`${JSON.stringify(canonical(envelope))}\n`); return; }
    const planPath = text(a['--plan-file'], '--plan-file'); const digest = hex(a['--plan-sha256'], 64, '--plan-sha256'); const approved = readPlan(planPath, digest, ctx, coordinates);
    if (operation === 'verify') { const live = await loadLive(prisma, ctx, coordinates); if (live.targets.classification !== 'EXACT_RERUN_NOOP' || !same(buildPlan(live, ctx, coordinates), approved.plan)) refuse('verify detected Audience, target, destination, audit, or non-target drift'); report('verify', 'VERIFIED', approved.digest, 'EXACT_RERUN_NOOP', { principals: 0, clients: 0, grants: 0, audits: 0, destinations: 0, secrets_generated: 0 }, live.nonTargetDigest); return; }
    if (!conformanceMode && process.env.AUTH_NOTIFICATION_INGRESS_PRODUCTION_APPLY !== PROD_CONFIRMATION) refuse('production APPLY confirmation gate absent'); const auth = approval(readFifo(a['--approval-fd'] as string | undefined, 'owner approval'), approved.digest, ctx, coordinates); await apply(prisma, ctx, approved, auth, coordinates);
  } finally { await prisma.$disconnect(); }
}
main().catch((error: unknown) => { const code = typeof error === 'object' && error !== null && 'code' in error && typeof error.code === 'string' && /^[A-Z0-9]{1,16}$/.test(error.code) ? error.code : 'UNCLASSIFIED'; const metaCode = typeof error === 'object' && error !== null && 'meta' in error && typeof error.meta === 'object' && error.meta !== null && 'code' in error.meta && typeof error.meta.code === 'string' && /^[A-Z0-9]{1,16}$/.test(error.meta.code) ? error.meta.code : 'NONE'; const message = error instanceof Refusal ? error.message : `unknown query or operator failure (${code}:${metaCode})`; process.stderr.write(`${JSON.stringify({ schema_version: 1, result: 'REFUSED', error: message })}\n`); process.exitCode = error instanceof Refusal ? 20 : 21; });
