import { createHash, randomBytes, randomUUID, scryptSync, timingSafeEqual } from 'node:crypto';
import { execFileSync } from 'node:child_process';
import {
  chmodSync, closeSync, existsSync, fchmodSync, fstatSync, fsyncSync, lstatSync, mkdirSync,
  openSync, readFileSync, readSync, readdirSync, realpathSync, renameSync, unlinkSync, writeSync,
} from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import type { Stats } from 'node:fs';
import { Prisma, PrismaClient } from '@prisma/client';

/*
 * Closed operator for AUTH_SERVICE_AGENT_CORE_NOTIFICATION_INGRESS_SERVICE_CREDENTIAL_GRANT_V1.
 * Default = read-only plan. Production apply is impossible without a clean exact HEAD, accepted
 * Spec, an exact plan file+digest, and a FIFO-delivered owner approval bound to this environment,
 * implementation, digest and execution window. Conformance has a separate descriptor-only seam.
 */
const ROOT = fileURLToPath(new URL('../', import.meta.url));
const SPEC_ID = 'AUTH_SERVICE_AGENT_CORE_NOTIFICATION_INGRESS_SERVICE_CREDENTIAL_GRANT_V1';
const SPEC_PATH = `docs/specs/${SPEC_ID}.md`;
const PLAN_VERSION = `${SPEC_ID}_PLAN_1`;
const MIGRATION_ID = 'notification-ingress-service-credential-grant-v1';
const AUDIENCE_ID = 'agent-core-notification-ingress-v1';
const SCOPE = 'notification.deliver';
const GLOBAL_LOCK = 741_903_511;
const PROD_CONFIRMATION = 'AUTHORIZED_NOTIFICATION_INGRESS_PHASE_B_APPLY_V1';
const REPORT_KEYS = ['schema_version', 'operation', 'result', 'plan_sha256', 'classification', 'writes', 'non_target_digest', 'residual_coordinates'] as const;
const AUDIT_KEYS = ['change_id', 'migration_id', 'source_git_commit', 'operator_id', 'approval_ref', 'reason', 'client_id', 'change_type', 'expected_grant_version', 'resulting_grant_version', 'before_value', 'after_value', 'timestamp'] as const;

type Json = null | boolean | number | string | Json[] | { [key: string]: Json };
type Db = PrismaClient | Prisma.TransactionClient;
type Target = {
  caller: 'svc-forum' | 'svc-workflow'; principalExternalRef: string; principalDisplayName: string;
  clientExternalRef: string; clientId: string; productionDestination: string;
};
type Destination = { path: string; exists: boolean; mode: number | null; uid: number | null; keys: string[]; exact: boolean; secret: string | null; bytes: Buffer | null };
type Approval = { spec_id: string; spec_revision: string; implementation_commit: string; plan_sha256: string; environment: string; window_not_before: string; window_not_after: string; operator_id: string; approval_ref: string };
type Context = { url: string; environment: string; destinations: Record<string, string>; expectedUid: number; markerPath: string; conformance: boolean; faultInjection: string };
type TargetState = { classification: 'ABSENT' | 'EXACT_RERUN_NOOP'; safe: Json; internalIds: Record<string, string>; secretHashes: Record<string, string>; audits: Json[] };
type Live = { databaseIdentity: { database: string; address: string; port: number }; audience: Json; targets: TargetState; destinations: Json[]; destinationRuntime: Destination[]; nonTargetDigest: string; nonTargetCounts: { clients: number; grants: number } };
type Plan = { plan_version: string; spec_id: string; spec_revision: string; implementation_commit: string; environment: string; database_identity: { database: string; address: string; port: number }; classification: 'CREATE' | 'EXACT_RERUN_NOOP'; audience: Json; targets: Json; destinations: Json[]; non_target: { digest_algorithm: string; digest: string; client_count: number; grant_count: number } };
type JournalFile = { caller: string; destination_path: string; stage_path: string; backup_path: string; preimage: { exists: boolean; mode: number | null; uid: number | null; size: number; sha256: string | null; managed_keys_absent: true }; installed_sha256: string | null; backup_state: 'pending' | 'ready' | 'restored' | 'removed'; stage_state: 'pending' | 'ready' | 'removed'; install_state: 'pending' | 'installed' | 'restored' };
type JournalIds = { caller: string; principal_id: string; client_internal_id: string; create_audit_id: string; revoke_audit_id: string };
type Journal = {
  schema_version: 2; run_id: string; result: 'APPLY_IN_PROGRESS' | 'RECOVERY_REQUIRED' | 'COMMIT_FINALIZED'; spec_id: string; spec_revision: string; implementation_commit: string; plan_sha256: string; environment: string;
  database_identity: { database: string; address: string; port: number }; ids: JournalIds[]; files: JournalFile[];
  db: { tx_state: 'not_started' | 'open' | 'rows_written' | 'committing' | 'committed' | 'rolled_back' | 'compensated' | 'unknown'; commit_state: 'not_attempted' | 'acknowledged' | 'uncertain' | 'none' | 'full' | 'partial'; compensation_state: 'not_required' | 'pending' | 'complete' | 'failed' };
  audit_binding: { operator_id: string; approval_ref: string; reason: string }; prestate: { target_classification: 'ABSENT'; target_projection: Json; non_target_digest: string; non_target_client_count: number; non_target_grant_count: number }; secrets_generated: 0 | 2; residual_coordinates: string[];
};

const TARGETS: readonly Target[] = Object.freeze([
  Object.freeze({ caller: 'svc-forum', principalExternalRef: 'service:v1:principal:svc-forum', principalDisplayName: 'svc-forum service', clientExternalRef: 'service:v1:client:svc-forum:agent-core-notification-ingress-v1', clientId: 'mc_Ez8kTAKKvcf2pF40aoUM4q9M', productionDestination: '/Users/yanfenma/.local/services/svc-forum/notification-ingress.env' }),
  Object.freeze({ caller: 'svc-workflow', principalExternalRef: 'service:v1:principal:svc-workflow', principalDisplayName: 'svc-workflow service', clientExternalRef: 'service:v1:client:svc-workflow:agent-core-notification-ingress-v1', clientId: 'mc_uYu1fDfNHjzUlRQGJdTajz9n', productionDestination: '/Users/yanfenma/.local/services/svc-workflow/.env' }),
]);

class Refusal extends Error { constructor(message: string) { super(message); this.name = 'Refusal'; } }
function refuse(message: string): never { throw new Refusal(message); }
function object(value: unknown, label: string): Record<string, unknown> { if (typeof value !== 'object' || value === null || Array.isArray(value)) refuse(`${label} must be an object`); return value as Record<string, unknown>; }
function exactKeys(value: Record<string, unknown>, keys: readonly string[], label: string): void { const a = Object.keys(value).sort(); const e = [...keys].sort(); if (a.length !== e.length || a.some((v, i) => v !== e[i])) refuse(`${label} has missing or additional fields`); }
function text(value: unknown, label: string, max = 2048): string { if (typeof value !== 'string' || value.length === 0 || Buffer.byteLength(value) > max) refuse(`${label} is invalid`); return value; }
function hex(value: unknown, length: number, label: string): string { const result = text(value, label); if (!new RegExp(`^[0-9a-f]{${length}}$`).test(result)) refuse(`${label} must be lowercase ${length}-hex`); return result; }
function canonical(value: unknown): unknown { if (Array.isArray(value)) return value.map(canonical); if (value !== null && typeof value === 'object') return Object.fromEntries(Object.keys(value as Record<string, unknown>).sort().map((k) => [k, canonical((value as Record<string, unknown>)[k])])); return value; }
function canonicalBytes(value: unknown): Buffer { return Buffer.from(JSON.stringify(canonical(value)), 'utf8'); }
function sha256(value: Buffer | string): string { return createHash('sha256').update(value).digest('hex'); }
function same(a: unknown, b: unknown): boolean { return canonicalBytes(a).equals(canonicalBytes(b)); }
function ascii(a: string, b: string): number { return Buffer.compare(Buffer.from(a), Buffer.from(b)); }
function dateJson(value: unknown): string | null { return value instanceof Date ? value.toISOString() : value === null ? null : String(value); }
function report(operation: string, result: string, planDigest: string | null, classification: string | null, writes: Record<string, number>, nonTarget: string | null, residual: string[] = []): void {
  const value = { schema_version: 1, operation, result, plan_sha256: planDigest, classification, writes, non_target_digest: nonTarget, residual_coordinates: residual };
  exactKeys(value, REPORT_KEYS, 'report'); process.stdout.write(`${JSON.stringify(value)}\n`);
}

// Reject duplicate decoded object keys before JSON.parse (approval/plan/descriptor are authority inputs).
function parseUnique(bytes: Buffer, label: string, limit = 1024 * 1024): Json {
  if (bytes.length === 0 || bytes.length > limit || !Buffer.from(bytes.toString('utf8')).equals(bytes)) refuse(`${label} bytes are invalid`);
  const input = bytes.toString('utf8'); let i = 0;
  const ws = () => { while (/[\x20\x09\x0a\x0d]/.test(input[i] ?? 'x')) i += 1; };
  const str = (): string => { const start = i; if (input[i++] !== '"') refuse(`${label} JSON invalid`); let esc = false; while (i < input.length) { const c = input[i++]; if (c === '\\') { esc = true; i += 1; } else if (c === '"') { try { return JSON.parse(input.slice(start, i)) as string; } catch { refuse(`${label} JSON string invalid`); } } else if (c.charCodeAt(0) < 32) refuse(`${label} JSON string invalid`); } refuse(`${label} JSON unterminated`); };
  const val = (): void => { ws(); const c = input[i]; if (c === '{') { i += 1; ws(); const keys = new Set<string>(); if (input[i] === '}') { i += 1; return; } while (true) { ws(); const k = str(); if (keys.has(k)) refuse(`${label} duplicate member`); keys.add(k); ws(); if (input[i++] !== ':') refuse(`${label} JSON invalid`); val(); ws(); const sep = input[i++]; if (sep === '}') return; if (sep !== ',') refuse(`${label} JSON invalid`); } } if (c === '[') { i += 1; ws(); if (input[i] === ']') { i += 1; return; } while (true) { val(); ws(); const sep = input[i++]; if (sep === ']') return; if (sep !== ',') refuse(`${label} JSON invalid`); } } if (c === '"') { str(); return; } const m = /^(?:true|false|null|-?(?:0|[1-9]\d*)(?:\.\d+)?(?:[eE][+-]?\d+)?)/.exec(input.slice(i)); if (!m) refuse(`${label} JSON invalid`); i += m[0].length; };
  val(); ws(); if (i !== input.length) refuse(`${label} trailing bytes`); try { return JSON.parse(input) as Json; } catch { refuse(`${label} JSON invalid`); }
}
function readFifo(fdValue: string | undefined, label: string): Json { if (!fdValue || !/^(?:[3-9]|[1-9]\d+)$/.test(fdValue)) refuse(`${label} descriptor invalid`); const fd = Number(fdValue); if (!fstatSync(fd).isFIFO()) refuse(`${label} must be a FIFO`); const chunks: Buffer[] = []; let total = 0; while (true) { const b = Buffer.allocUnsafe(65536); const n = readSync(fd, b, 0, b.length, null); if (n === 0) break; total += n; if (total > 1024 * 1024) { closeSync(fd); refuse(`${label} too large`); } chunks.push(b.subarray(0, n)); } closeSync(fd); return parseUnique(Buffer.concat(chunks), label); }

function repoCoordinates(requireClean: boolean): { implementation: string; specRevision: string } {
  const git = '/usr/bin/git'; const top = execFileSync(git, ['-C', ROOT, 'rev-parse', '--show-toplevel'], { encoding: 'utf8' }).trim(); if (`${top}/` !== ROOT) refuse('repository root mismatch');
  if (requireClean && execFileSync(git, ['-C', ROOT, 'status', '--porcelain', '--untracked-files=all'], { encoding: 'utf8' }) !== '') refuse('production apply requires a clean worktree');
  const implementation = hex(execFileSync(git, ['-C', ROOT, 'rev-parse', 'HEAD'], { encoding: 'utf8' }).trim(), 40, 'HEAD');
  const specRevision = hex(execFileSync(git, ['-C', ROOT, 'rev-parse', `HEAD:${SPEC_PATH}`], { encoding: 'utf8' }).trim(), 40, 'Spec blob');
  const spec = readFileSync(resolve(ROOT, SPEC_PATH), 'utf8');
  if (!spec.startsWith('---\n') || !spec.includes(`spec_id: ${SPEC_ID}`) || !spec.includes('status: accepted') || !spec.includes('implementation_authority: contracts') || !spec.includes('production_apply_authority: none')) refuse('governing Spec lifecycle/authority mismatch');
  return { implementation, specRevision };
}

function parseEnv(bytes: Buffer): Map<string, string> { const result = new Map<string, string>(); for (const line of bytes.toString('utf8').split(/\r?\n/)) { if (line === '' || /^\s*#/.test(line)) continue; const m = /^([A-Z][A-Z0-9_]*)=(.*)$/.exec(line); if (!m || result.has(m[1])) refuse('destination has malformed or duplicate environment keys'); result.set(m[1], m[2]); } return result; }
function lstatMaybe(path: string): Stats | null { try { return lstatSync(path); } catch (error) { if (typeof error === 'object' && error !== null && 'code' in error && error.code === 'ENOENT') return null; throw error; } }
function rejectSymlinkParents(path: string): void { let current = dirname(path); while (true) { const st = lstatMaybe(current); if (st && (!st.isDirectory() || st.isSymbolicLink())) refuse('destination parent chain must contain only real directories'); const parent = dirname(current); if (parent === current) break; current = parent; } }
function destination(path: string, expectedUid: number, target: Target): Destination {
  if (!path.startsWith('/') || path.includes('\0')) refuse('destination must be absolute'); rejectSymlinkParents(path);
  const st = lstatMaybe(path); if (st === null) return { path, exists: false, mode: null, uid: null, keys: [], exact: false, secret: null, bytes: null };
  if (!st.isFile() || st.isSymbolicLink() || st.nlink !== 1) refuse('destination must be one regular non-linked file');
  const bytes = readFileSync(path); const env = parseEnv(bytes); const client = env.get('AUTH_NOTIFICATION_INGRESS_CLIENT_ID') ?? null; const secret = env.get('AUTH_NOTIFICATION_INGRESS_CLIENT_SECRET') ?? null;
  const exact = (st.mode & 0o777) === 0o600 && st.uid === expectedUid && client === target.clientId && typeof secret === 'string' && secret.length > 0;
  return { path, exists: true, mode: st.mode & 0o777, uid: st.uid, keys: [...env.keys()].sort(ascii), exact, secret, bytes };
}
function safeUnmanagedPreimage(d: Destination, expectedUid: number): boolean { return d.exists && d.mode === 0o600 && d.uid === expectedUid && !d.keys.includes('AUTH_NOTIFICATION_INGRESS_CLIENT_ID') && !d.keys.includes('AUTH_NOTIFICATION_INGRESS_CLIENT_SECRET'); }
function safeDestination(d: Destination): Json { return { path: d.path, exists: d.exists, mode: d.mode, uid: d.uid, keys_present: d.keys, exact_metadata_and_keys: d.exact }; }
function destinationBytes(pre: Destination, target: Target, secret: string): Buffer { const env = pre.bytes ? parseEnv(pre.bytes) : new Map<string, string>(); env.set('AUTH_NOTIFICATION_INGRESS_CLIENT_ID', target.clientId); env.set('AUTH_NOTIFICATION_INGRESS_CLIENT_SECRET', secret); return Buffer.from([...env.entries()].sort(([a], [b]) => ascii(a, b)).map(([k, v]) => `${k}=${v}\n`).join(''), 'utf8'); }
function syncDirectory(path: string): void { const fd = openSync(dirname(path), 'r'); try { fsyncSync(fd); } finally { closeSync(fd); } }
function deterministicUuid(runId: string, label: string): string { const bytes = createHash('sha256').update(`${runId}\0${label}`).digest().subarray(0, 16); bytes[6] = (bytes[6] & 0x0f) | 0x40; bytes[8] = (bytes[8] & 0x3f) | 0x80; const h = bytes.toString('hex'); return `${h.slice(0, 8)}-${h.slice(8, 12)}-${h.slice(12, 16)}-${h.slice(16, 20)}-${h.slice(20)}`; }
function fault(ctx: Context, point: string): void { if (ctx.faultInjection === `crash:${point}`) process.exit(86); if (ctx.faultInjection === `fail:${point}`) refuse(`conformance fault at ${point}`); }
function markerStat(ctx: Context): Stats { const st = lstatSync(ctx.markerPath); if (!st.isFile() || st.isSymbolicLink() || st.nlink !== 1 || st.uid !== ctx.expectedUid || (st.mode & 0o777) !== 0o600) refuse('schema-v2 recovery journal metadata invalid'); return st; }
function writeJournal(ctx: Context, journal: Journal, create = false): void {
  mkdirSync(dirname(ctx.markerPath), { recursive: true, mode: 0o700 }); rejectSymlinkParents(ctx.markerPath);
  if (create && existsSync(ctx.markerPath)) refuse('recovery journal already exists'); if (!create) markerStat(ctx);
  const temp = `${ctx.markerPath}.tmp-${journal.run_id}`; if (existsSync(temp)) unlinkSync(temp); const fd = openSync(temp, 'wx', 0o600);
  try { fchmodSync(fd, 0o600); writeSync(fd, Buffer.from(`${JSON.stringify(canonical(journal))}\n`)); fsyncSync(fd); } finally { closeSync(fd); }
  renameSync(temp, ctx.markerPath); syncDirectory(ctx.markerPath);
}
function readJournal(ctx: Context): Journal {
  markerStat(ctx); const value = object(parseUnique(readFileSync(ctx.markerPath), 'schema-v2 recovery journal'), 'schema-v2 recovery journal');
  exactKeys(value, ['schema_version', 'run_id', 'result', 'spec_id', 'spec_revision', 'implementation_commit', 'plan_sha256', 'environment', 'database_identity', 'ids', 'files', 'db', 'audit_binding', 'prestate', 'secrets_generated', 'residual_coordinates'], 'schema-v2 recovery journal');
  if (value.schema_version !== 2 || value.spec_id !== SPEC_ID || value.environment !== ctx.environment || !/^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/.test(String(value.run_id)) || !Array.isArray(value.ids) || value.ids.length !== 2 || !Array.isArray(value.files) || value.files.length !== 2 || !Array.isArray(value.residual_coordinates)) refuse('schema-v2 recovery journal binding invalid');
  exactKeys(object(value.database_identity, 'journal database_identity'), ['database', 'address', 'port'], 'journal database_identity'); exactKeys(object(value.db, 'journal db'), ['tx_state', 'commit_state', 'compensation_state'], 'journal db'); exactKeys(object(value.audit_binding, 'journal audit_binding'), ['operator_id', 'approval_ref', 'reason'], 'journal audit_binding'); exactKeys(object(value.prestate, 'journal prestate'), ['target_classification', 'target_projection', 'non_target_digest', 'non_target_client_count', 'non_target_grant_count'], 'journal prestate');
  const runId = String(value.run_id); for (const [i, raw] of (value.ids as unknown[]).entries()) { const id = object(raw, 'journal id'); exactKeys(id, ['caller', 'principal_id', 'client_internal_id', 'create_audit_id', 'revoke_audit_id'], 'journal id'); const target = TARGETS[i]; if (id.caller !== target.caller || id.principal_id !== deterministicUuid(runId, `${target.caller}:principal`) || id.client_internal_id !== deterministicUuid(runId, `${target.caller}:client`) || id.create_audit_id !== deterministicUuid(runId, `${target.caller}:create-audit`) || id.revoke_audit_id !== deterministicUuid(runId, `${target.caller}:revoke-audit`)) refuse('journal deterministic IDs mismatch'); }
  for (const [i, raw] of (value.files as unknown[]).entries()) { const file = object(raw, 'journal file'); exactKeys(file, ['caller', 'destination_path', 'stage_path', 'backup_path', 'preimage', 'installed_sha256', 'backup_state', 'stage_state', 'install_state'], 'journal file'); const preimage = object(file.preimage, 'journal preimage'); exactKeys(preimage, ['exists', 'mode', 'uid', 'size', 'sha256', 'managed_keys_absent'], 'journal preimage'); const target = TARGETS[i]; const destinationPath = ctx.destinations[target.caller]; if (file.caller !== target.caller || file.destination_path !== destinationPath || file.stage_path !== `${destinationPath}.nsc-stage-${runId}-${i}` || file.backup_path !== `${destinationPath}.nsc-backup-${runId}-${i}`) refuse('journal file coordinates mismatch'); const exists = preimage.exists === true; const metadataValid = exists ? preimage.mode === 0o600 && preimage.uid === ctx.expectedUid && Number.isSafeInteger(preimage.size) && (preimage.size as number) >= 0 && /^[0-9a-f]{64}$/.test(String(preimage.sha256)) : preimage.mode === null && preimage.uid === null && preimage.size === 0 && preimage.sha256 === null; if (!metadataValid || preimage.managed_keys_absent !== true || !['pending', 'ready', 'restored', 'removed'].includes(String(file.backup_state)) || !['pending', 'ready', 'removed'].includes(String(file.stage_state)) || !['pending', 'installed', 'restored'].includes(String(file.install_state)) || (file.installed_sha256 !== null && !/^[0-9a-f]{64}$/.test(String(file.installed_sha256)))) refuse('journal file state invalid'); }
  if (!['APPLY_IN_PROGRESS', 'RECOVERY_REQUIRED', 'COMMIT_FINALIZED'].includes(String(value.result)) || !['not_started', 'open', 'rows_written', 'committing', 'committed', 'rolled_back', 'compensated', 'unknown'].includes(String((value.db as Record<string, unknown>).tx_state)) || !['not_attempted', 'acknowledged', 'uncertain', 'none', 'full', 'partial'].includes(String((value.db as Record<string, unknown>).commit_state)) || !['not_required', 'pending', 'complete', 'failed'].includes(String((value.db as Record<string, unknown>).compensation_state)) || (value.secrets_generated !== 0 && value.secrets_generated !== 2) || value.residual_coordinates.some((v) => typeof v !== 'string')) refuse('journal state enum invalid');
  const specRevision = hex(value.spec_revision, 40, 'journal spec_revision'); hex(value.implementation_commit, 40, 'journal implementation_commit'); const planDigest = hex(value.plan_sha256, 64, 'journal plan_sha256'); const prestate = value.prestate as Record<string, unknown>; hex(prestate.non_target_digest, 64, 'journal non_target_digest'); const audit = value.audit_binding as Record<string, unknown>; const database = value.database_identity as Record<string, unknown>; if (prestate.target_classification !== 'ABSENT' || !Array.isArray(prestate.target_projection) || !Number.isSafeInteger(prestate.non_target_client_count) || (prestate.non_target_client_count as number) < 0 || !Number.isSafeInteger(prestate.non_target_grant_count) || (prestate.non_target_grant_count as number) < 0 || typeof database.database !== 'string' || typeof database.address !== 'string' || !Number.isInteger(database.port) || !/^[A-Za-z0-9][A-Za-z0-9._:@/-]{0,127}$/.test(String(audit.operator_id)) || typeof audit.approval_ref !== 'string' || audit.reason !== `spec_blob=${specRevision};plan_sha256=${planDigest};environment=${ctx.environment}`) refuse('journal authority or prestate binding invalid');
  return value as unknown as Journal;
}
function removeJournal(ctx: Context): void { unlinkSync(ctx.markerPath); syncDirectory(ctx.markerPath); }
function writeBackup(path: string, bytes: Buffer): void { const fd = openSync(path, 'wx', 0o600); try { fchmodSync(fd, 0o600); writeSync(fd, bytes); fsyncSync(fd); } finally { closeSync(fd); } syncDirectory(path); }
function stageAt(path: string, bytes: Buffer): void { const parent = lstatSync(dirname(path)); if (!parent.isDirectory() || parent.isSymbolicLink() || (parent.mode & 0o022) !== 0) refuse('stage parent unsafe'); const fd = openSync(path, 'wx', 0o600); try { fchmodSync(fd, 0o600); writeSync(fd, bytes); fsyncSync(fd); } finally { closeSync(fd); } syncDirectory(path); }
function destinationsEqual(a: Destination[], b: Destination[]): boolean { return a.length === b.length && a.every((v, i) => v.path === b[i].path && v.exists === b[i].exists && v.mode === b[i].mode && v.uid === b[i].uid && ((v.bytes === null && b[i].bytes === null) || (v.bytes !== null && b[i].bytes !== null && v.bytes.equals(b[i].bytes)))); }
function cleanStageResidue(ctx: Context, journal: Journal): string[] { const residual: string[] = []; for (const file of journal.files) { const dir = dirname(file.destination_path); const base = file.destination_path.slice(dir.length + 1); const owned = new Set([file.stage_path, `${file.destination_path}.nsc-stage-${journal.run_id}-restore`]); try { for (const name of readdirSync(dir)) if (name.startsWith(`${base}.nsc-stage-`)) { const path = resolve(dir, name); if (!owned.has(path)) { residual.push(`unowned-stage:${path}`); continue; } try { const st = lstatSync(path); if (!st.isFile() || st.isSymbolicLink() || st.nlink !== 1 || st.uid !== ctx.expectedUid || (st.mode & 0o777) !== 0o600) throw new Error('unsafe residue'); unlinkSync(path); } catch { residual.push(`stage:${path}`); } } syncDirectory(file.destination_path); } catch { residual.push(`stage-directory:${dir}`); } } return residual; }

function hashSecret(secret: string): string { const salt = randomBytes(16).toString('hex'); return `${salt}:${scryptSync(secret, salt, 64, { N: 16384, r: 8, p: 1 }).toString('hex')}`; }
function verifySecret(secret: string, stored: string): boolean { const m = /^([0-9a-f]{32}):([0-9a-f]{128})$/.exec(stored); if (!m) return false; const actual = scryptSync(secret, m[1], 64, { N: 16384, r: 8, p: 1 }); const expected = Buffer.from(m[2], 'hex'); return actual.length === expected.length && timingSafeEqual(actual, expected); }
function safeAfter(target: Target, principalId: string): Prisma.InputJsonObject { return { client_id: target.clientId, client_kind: 'machine', principal_id: principalId, principal_type: 'service', human_audience_grants: [], machine_access_grants: { [AUDIENCE_ID]: [SCOPE] }, delegation_grants: {}, status: 'active', version: 1 }; }

async function audienceProjection(db: Db): Promise<Json> { const rows = await db.authAudience.findMany({ where: { audienceId: AUDIENCE_ID } }); if (rows.length !== 1) refuse('Audience absent or duplicate'); const a = rows[0]; const exact = a.resourceService === AUDIENCE_ID && a.scopeNamespace === 'notification' && same(a.acceptedPrincipalTypes, ['service']) && same(a.registeredScopes, [SCOPE]) && !a.humanAccessEnabled && a.machineAccessEnabled && !a.delegatedAccessEnabled && a.status === 'active' && a.freezeReady;
  if (!exact) refuse('Audience mismatch'); return { audience_id: a.audienceId, resource_service: a.resourceService, scope_namespace: a.scopeNamespace, accepted_principal_types: a.acceptedPrincipalTypes, registered_scopes: a.registeredScopes, human_access_enabled: a.humanAccessEnabled, machine_access_enabled: a.machineAccessEnabled, delegated_access_enabled: a.delegatedAccessEnabled, status: a.status, freeze_ready: a.freezeReady, version: a.version, created_at: a.createdAt.toISOString(), updated_at: a.updatedAt.toISOString() }; }

async function targetState(db: Db, destinations: Destination[], expectedUid: number, coordinates: { implementation: string; specRevision: string }, planDigestForAudit?: string, approval?: Approval): Promise<TargetState> {
  const safe: Json[] = []; const internalIds: Record<string, string> = {}; const secretHashes: Record<string, string> = {}; const auditsSafe: Json[] = []; let absent = 0; let exact = 0;
  for (const [index, target] of TARGETS.entries()) {
    const principals = await db.machinePrincipal.findMany({ where: { externalRef: target.principalExternalRef } });
    const clients = await db.machineClient.findMany({ where: { OR: [{ externalRef: target.clientExternalRef }, { clientId: target.clientId }] }, include: { accessGrants: true, trustedProxy: { include: { delegationGrants: true } } } });
    const audits = await db.grantChangeAudit.findMany({ where: { clientId: target.clientId }, orderBy: [{ timestamp: 'asc' }, { id: 'asc' }] });
    if (principals.length === 0 && clients.length === 0 && audits.length === 0 && (!destinations[index].exists || safeUnmanagedPreimage(destinations[index], expectedUid))) { absent += 1; safe.push({ caller: target.caller, state: 'ABSENT', desired: { principal: { principal_type: 'service', agent_id: null, owner_user_id: null, external_ref: target.principalExternalRef, display_name: target.principalDisplayName, status: 'active', disabled_at: null }, client: { client_id: target.clientId, external_ref: target.clientExternalRef, principal_external_ref: target.principalExternalRef, status: 'active', allowed_resources: [], allowed_scopes: [], rotated_at: null, revoked_at: null }, grant: { audience_id: AUDIENCE_ID, scopes: [SCOPE], version: 1 }, destination: { path: destinations[index].path, owner: 'yanfenma', mode: 0o600, keys_present: ['AUTH_NOTIFICATION_INGRESS_CLIENT_ID', 'AUTH_NOTIFICATION_INGRESS_CLIENT_SECRET'] } } }); continue; }
    if (principals.length !== 1 || clients.length !== 1 || audits.length !== 1) refuse(`${target.caller} target is partial, duplicate, ambiguous, or audit-mismatched`);
    const p = principals[0]; const c = clients[0]; const g = c.accessGrants;
    const shape = p.externalRef === target.principalExternalRef && p.principalType === 'service' && p.agentId === null && p.ownerUserId === null && p.displayName === target.principalDisplayName && p.status === 'active' && p.disabledAt === null && c.externalRef === target.clientExternalRef && c.clientId === target.clientId && c.machinePrincipalId === p.id && c.status === 'active' && c.allowedResources.length === 0 && c.allowedScopes.length === 0 && c.rotatedAt === null && c.revokedAt === null && c.trustedProxy === null && g.length === 1 && g[0].audienceId === AUDIENCE_ID && same(g[0].scopes, [SCOPE]) && g[0].version === 1 && destinations[index].exact && destinations[index].secret !== null && verifySecret(destinations[index].secret!, c.secretHash);
    const after = safeAfter(target, p.id); const audit = audits[0]; const reasonExpected = planDigestForAudit && approval ? `spec_blob=${coordinates.specRevision};plan_sha256=${planDigestForAudit};environment=${approval.environment}` : null;
    const closedReason = new RegExp(`^spec_blob=${coordinates.specRevision};plan_sha256=[0-9a-f]{64};environment=[a-z0-9][a-z0-9._-]{0,63}$`).test(audit.reason);
    const auditShape = audit.migrationId === MIGRATION_ID && audit.sourceGitCommit === coordinates.implementation && audit.clientId === target.clientId && audit.changeType === 'create' && audit.expectedGrantVersion === null && audit.resultingGrantVersion === 1 && audit.beforeValue === null && same(audit.afterValue, after) && audit.operatorId.length > 0 && audit.approvalRef.length > 0 && closedReason && (reasonExpected === null || (audit.reason === reasonExpected && audit.operatorId === approval!.operator_id && audit.approvalRef === approval!.approval_ref));
    if (!shape || !auditShape) refuse(`${target.caller} target has SHAPE_MISMATCH, DESTINATION_MISMATCH, or AUDIT_MISMATCH`);
    exact += 1; internalIds[target.caller] = c.id; secretHashes[target.caller] = c.secretHash;
    const safeAudit = { change_id: audit.id, migration_id: audit.migrationId, source_git_commit: audit.sourceGitCommit, operator_id: audit.operatorId, approval_ref: audit.approvalRef, reason: audit.reason, client_id: audit.clientId, change_type: audit.changeType, expected_grant_version: audit.expectedGrantVersion, resulting_grant_version: audit.resultingGrantVersion, before_value: audit.beforeValue as Json, after_value: audit.afterValue as Json, timestamp: audit.timestamp.toISOString() }; exactKeys(safeAudit, AUDIT_KEYS, 'audit envelope'); auditsSafe.push(safeAudit);
    safe.push({ caller: target.caller, state: 'EXACT', principal: { id: p.id, principal_type: p.principalType, external_ref: p.externalRef, display_name: p.displayName, status: p.status }, client: { id: c.id, client_id: c.clientId, external_ref: c.externalRef, machine_principal_id: c.machinePrincipalId, status: c.status, allowed_resources: c.allowedResources, allowed_scopes: c.allowedScopes }, grant: { audience_id: g[0].audienceId, scopes: g[0].scopes, version: g[0].version }, secret_to_hash_match: true, audit: safeAudit });
  }
  if (absent === TARGETS.length) return { classification: 'ABSENT', safe, internalIds, secretHashes, audits: auditsSafe };
  if (exact === TARGETS.length) return { classification: 'EXACT_RERUN_NOOP', safe, internalIds, secretHashes, audits: auditsSafe };
  refuse('mixed target state is PARTIAL');
}

type RawClient = { id: string; client_id: string; machine_principal_id: string; secret_hash: string; external_ref: string | null; status: string; allowed_resources: string[]; allowed_scopes: string[]; created_at: Date; updated_at: Date; rotated_at: Date | null; revoked_at: Date | null };
type RawGrant = { machine_client_id: string; audience_id: string; scopes: string[]; version: number; created_at: Date; updated_at: Date };
function framed(rows: Array<{ kind: string; ordinal: string; fields: unknown[] }>): string { const hash = createHash('sha256'); for (const row of rows.sort((a, b) => ascii(`${a.kind}\0${a.ordinal}`, `${b.kind}\0${b.ordinal}`))) { for (const field of [row.kind, row.ordinal, ...row.fields]) { const bytes = canonicalBytes(field); hash.update(Buffer.from(`${bytes.length}:`, 'ascii')); hash.update(bytes); hash.update(Buffer.from(',', 'ascii')); } } return hash.digest('hex'); }
async function nonTarget(db: Db): Promise<{ digest: string; clients: number; grants: number }> {
  const clients = await db.$queryRaw<RawClient[]>(Prisma.sql`SELECT id, client_id, machine_principal_id, secret_hash, external_ref, status, allowed_resources, allowed_scopes, created_at, updated_at, rotated_at, revoked_at FROM machine_clients WHERE client_id NOT IN (${Prisma.join(TARGETS.map((t) => t.clientId))}) AND (external_ref IS NULL OR external_ref NOT IN (${Prisma.join(TARGETS.map((t) => t.clientExternalRef))})) ORDER BY id`);
  const targetIds = await db.$queryRaw<Array<{ id: string }>>(Prisma.sql`SELECT id FROM machine_clients WHERE client_id IN (${Prisma.join(TARGETS.map((t) => t.clientId))}) OR external_ref IN (${Prisma.join(TARGETS.map((t) => t.clientExternalRef))})`);
  const grants = targetIds.length === 0 ? await db.$queryRaw<RawGrant[]>`SELECT machine_client_id, audience_id, scopes, version, created_at, updated_at FROM machine_access_grants ORDER BY machine_client_id, audience_id` : await db.$queryRaw<RawGrant[]>(Prisma.sql`SELECT machine_client_id, audience_id, scopes, version, created_at, updated_at FROM machine_access_grants WHERE machine_client_id NOT IN (${Prisma.join(targetIds.map((r) => Prisma.sql`${r.id}::uuid`))}) ORDER BY machine_client_id, audience_id`);
  const rows: Array<{ kind: string; ordinal: string; fields: unknown[] }> = clients.map((c) => ({ kind: 'machine_client', ordinal: c.id, fields: [c.id, c.client_id, c.machine_principal_id, sha256(c.secret_hash), c.external_ref, c.status, c.allowed_resources, c.allowed_scopes, dateJson(c.created_at), dateJson(c.updated_at), dateJson(c.rotated_at), dateJson(c.revoked_at)] }));
  rows.push(...grants.map((g) => ({ kind: 'machine_access_grant', ordinal: `${g.machine_client_id}\0${g.audience_id}`, fields: [g.machine_client_id, g.audience_id, g.scopes, g.version, dateJson(g.created_at), dateJson(g.updated_at)] })));
  return { digest: framed(rows), clients: clients.length, grants: grants.length };
}

async function loadLive(db: Db, ctx: Context, coordinates: { implementation: string; specRevision: string }, planDigestForAudit?: string, approval?: Approval): Promise<Live> { const identities = await db.$queryRaw<Array<{ database: string; address: string; port: number }>>`SELECT current_database()::text AS database, COALESCE(inet_server_addr()::text, 'local') AS address, inet_server_port()::integer AS port`; if (identities.length !== 1 || !identities[0].database || !identities[0].address || !Number.isInteger(identities[0].port)) refuse('database environment identity unavailable'); const databaseIdentity = identities[0]; const audience = await audienceProjection(db); const destinationRuntime = TARGETS.map((t) => destination(ctx.destinations[t.caller], ctx.expectedUid, t)); const targets = await targetState(db, destinationRuntime, ctx.expectedUid, coordinates, planDigestForAudit, approval); const nt = await nonTarget(db); return { databaseIdentity, audience, targets, destinations: destinationRuntime.map(safeDestination), destinationRuntime, nonTargetDigest: nt.digest, nonTargetCounts: { clients: nt.clients, grants: nt.grants } }; }
function buildPlan(live: Live, ctx: Context, coordinates: { implementation: string; specRevision: string }): Plan { return { plan_version: PLAN_VERSION, spec_id: SPEC_ID, spec_revision: coordinates.specRevision, implementation_commit: coordinates.implementation, environment: ctx.environment, database_identity: live.databaseIdentity, classification: live.targets.classification === 'ABSENT' ? 'CREATE' : 'EXACT_RERUN_NOOP', audience: live.audience, targets: live.targets.safe, destinations: live.destinations, non_target: { digest_algorithm: 'SHA-256-length-delimited-v1', digest: live.nonTargetDigest, client_count: live.nonTargetCounts.clients, grant_count: live.nonTargetCounts.grants } }; }
function planEnvelope(plan: Plan): { plan: Plan; plan_sha256: string } { return { plan, plan_sha256: sha256(canonicalBytes(plan)) }; }
function readPlan(path: string, expectedDigest: string, ctx: Context, coordinates: { implementation: string; specRevision: string }): { plan: Plan; digest: string } { const parsed = object(parseUnique(readFileSync(path), 'plan'), 'plan envelope'); exactKeys(parsed, ['plan', 'plan_sha256'], 'plan envelope'); const plan = object(parsed.plan, 'plan') as unknown as Plan; const digest = hex(parsed.plan_sha256, 64, 'plan_sha256'); if (digest !== expectedDigest || sha256(canonicalBytes(plan)) !== digest) refuse('approved plan digest mismatch'); if (plan.plan_version !== PLAN_VERSION || plan.spec_id !== SPEC_ID || plan.spec_revision !== coordinates.specRevision || plan.implementation_commit !== coordinates.implementation || plan.environment !== ctx.environment) refuse('approved plan is stale or wrong-environment'); return { plan, digest }; }

function approval(value: Json, planDigest: string, ctx: Context, coordinates: { implementation: string; specRevision: string }): Approval { const v = object(value, 'approval'); const keys = ['spec_id', 'spec_revision', 'implementation_commit', 'plan_sha256', 'environment', 'window_not_before', 'window_not_after', 'operator_id', 'approval_ref']; exactKeys(v, keys, 'approval'); const result = Object.fromEntries(keys.map((k) => [k, text(v[k], `approval.${k}`)])) as Approval; if (result.spec_id !== SPEC_ID || result.spec_revision !== coordinates.specRevision || result.implementation_commit !== coordinates.implementation || result.plan_sha256 !== planDigest || result.environment !== ctx.environment) refuse('approval binding mismatch'); const before = Date.parse(result.window_not_before); const after = Date.parse(result.window_not_after); const now = Date.now(); if (!Number.isFinite(before) || !Number.isFinite(after) || now < before || now > after || after - before > 4 * 60 * 60 * 1000) refuse('approval execution window invalid'); if (!/^[A-Za-z0-9][A-Za-z0-9._:@/-]{0,127}$/.test(result.operator_id)) refuse('approval operator_id invalid'); const approvalRefOk = ctx.conformance ? /^conformance:\/\/owner-approval\/[a-z0-9-]+$/.test(result.approval_ref) : /^https:\/\/github\.com\/mayf3\/auth-service\/(?:issues|pull)\/[1-9][0-9]*(?:#(?:issuecomment|discussion_r)[-0-9]+)?$/.test(result.approval_ref); if (!approvalRefOk) refuse('approval_ref is not an allowed immutable review coordinate'); return result; }

async function createRows(tx: Prisma.TransactionClient, ctx: Context, journal: Journal, hashes: string[]): Promise<void> {
  for (const [i, target] of TARGETS.entries()) {
    const ids = journal.ids[i];
    const p = await tx.machinePrincipal.create({ data: { id: ids.principal_id, principalType: 'service', agentId: null, ownerUserId: null, displayName: target.principalDisplayName, externalRef: target.principalExternalRef, requestDigest: null, status: 'active' } }); fault(ctx, `principal:${target.caller}`);
    await tx.machineClient.create({ data: { id: ids.client_internal_id, clientId: target.clientId, machinePrincipalId: p.id, secretHash: hashes[i], externalRef: target.clientExternalRef, status: 'active', allowedResources: [], allowedScopes: [] } }); fault(ctx, `client:${target.caller}`);
    await tx.machineAccessGrant.create({ data: { machineClientId: ids.client_internal_id, audienceId: AUDIENCE_ID, scopes: [SCOPE], version: 1 } }); fault(ctx, `grant:${target.caller}`);
    const timestamp = new Date(); const after = safeAfter(target, p.id); const envelope = { change_id: ids.create_audit_id, migration_id: MIGRATION_ID, source_git_commit: journal.implementation_commit, operator_id: journal.audit_binding.operator_id, approval_ref: journal.audit_binding.approval_ref, reason: journal.audit_binding.reason, client_id: target.clientId, change_type: 'create', expected_grant_version: null, resulting_grant_version: 1, before_value: null, after_value: after, timestamp: timestamp.toISOString() }; exactKeys(envelope, AUDIT_KEYS, 'audit envelope');
    await tx.grantChangeAudit.create({ data: { id: ids.create_audit_id, migrationId: MIGRATION_ID, sourceGitCommit: journal.implementation_commit, operatorId: journal.audit_binding.operator_id, approvalRef: journal.audit_binding.approval_ref, reason: journal.audit_binding.reason, clientId: target.clientId, changeType: 'create', expectedGrantVersion: null, resultingGrantVersion: 1, beforeValue: Prisma.DbNull, afterValue: after, timestamp } }); fault(ctx, `audit:${target.caller}`);
  }
}

async function journalDbOutcome(db: Db, journal: Journal): Promise<'none' | 'full' | 'partial' | 'compensated'> {
  let none = 0; let full = 0; let compensated = 0;
  for (const [i, target] of TARGETS.entries()) {
    const ids = journal.ids[i];
    const principals = await db.machinePrincipal.findMany({ where: { OR: [{ id: ids.principal_id }, { externalRef: target.principalExternalRef }] } });
    const clients = await db.machineClient.findMany({ where: { OR: [{ id: ids.client_internal_id }, { clientId: target.clientId }, { externalRef: target.clientExternalRef }] }, include: { accessGrants: true } });
    const createAudits = await db.grantChangeAudit.findMany({ where: { OR: [{ id: ids.create_audit_id }, { clientId: target.clientId, changeType: 'create' }] } });
    const revokeAudits = await db.grantChangeAudit.findMany({ where: { OR: [{ id: ids.revoke_audit_id }, { clientId: target.clientId, changeType: 'revoke' }] } });
    if (principals.length === 0 && clients.length === 0 && createAudits.length === 0 && revokeAudits.length === 0) { none += 1; continue; }
    const after = safeAfter(target, ids.principal_id);
    const createExact = createAudits.length === 1 && createAudits[0].id === ids.create_audit_id && createAudits[0].migrationId === MIGRATION_ID && createAudits[0].sourceGitCommit === journal.implementation_commit && createAudits[0].operatorId === journal.audit_binding.operator_id && createAudits[0].approvalRef === journal.audit_binding.approval_ref && createAudits[0].reason === journal.audit_binding.reason && createAudits[0].clientId === target.clientId && createAudits[0].changeType === 'create' && createAudits[0].expectedGrantVersion === null && createAudits[0].resultingGrantVersion === 1 && createAudits[0].beforeValue === null && same(createAudits[0].afterValue, after);
    const revokeReason = `compensation_run=${journal.run_id};original_audit=${ids.create_audit_id};plan_sha256=${journal.plan_sha256}`;
    const revokeExact = revokeAudits.length === 1 && revokeAudits[0].id === ids.revoke_audit_id && revokeAudits[0].migrationId === MIGRATION_ID && revokeAudits[0].sourceGitCommit === journal.implementation_commit && revokeAudits[0].operatorId === journal.audit_binding.operator_id && revokeAudits[0].approvalRef === journal.audit_binding.approval_ref && revokeAudits[0].reason === revokeReason && revokeAudits[0].clientId === target.clientId && revokeAudits[0].changeType === 'revoke' && revokeAudits[0].expectedGrantVersion === 1 && revokeAudits[0].resultingGrantVersion === 2 && same(revokeAudits[0].beforeValue, after) && revokeAudits[0].afterValue === null;
    const p = principals[0]; const c = clients[0]; const g = c?.accessGrants[0];
    if (principals.length === 1 && p.id === ids.principal_id && p.externalRef === target.principalExternalRef && p.principalType === 'service' && p.agentId === null && p.ownerUserId === null && p.displayName === target.principalDisplayName && p.requestDigest === null && p.status === 'active' && p.disabledAt === null && clients.length === 1 && c.id === ids.client_internal_id && c.machinePrincipalId === ids.principal_id && c.clientId === target.clientId && c.externalRef === target.clientExternalRef && c.status === 'active' && c.allowedResources.length === 0 && c.allowedScopes.length === 0 && c.rotatedAt === null && c.revokedAt === null && /^[0-9a-f]{32}:[0-9a-f]{128}$/.test(c.secretHash) && c.accessGrants.length === 1 && g.audienceId === AUDIENCE_ID && same(g.scopes, [SCOPE]) && g.version === 1 && createExact && revokeAudits.length === 0) { full += 1; continue; }
    if (principals.length === 0 && clients.length === 0 && createExact && revokeExact) { compensated += 1; continue; }
    return 'partial';
  }
  if (none === 2) return 'none'; if (full === 2) return 'full'; if (compensated === 2) return 'compensated'; return 'partial';
}
async function compensate(db: PrismaClient, ctx: Context, journal: Journal): Promise<void> {
  journal.db.compensation_state = 'pending'; writeJournal(ctx, journal); fault(ctx, 'compensation-start');
  await db.$transaction(async (tx) => {
    await tx.$executeRawUnsafe('LOCK TABLE machine_principals IN SHARE ROW EXCLUSIVE MODE'); await tx.$executeRawUnsafe('LOCK TABLE machine_clients IN SHARE ROW EXCLUSIVE MODE'); await tx.$executeRawUnsafe('LOCK TABLE machine_access_grants IN SHARE ROW EXCLUSIVE MODE'); await tx.$executeRawUnsafe('LOCK TABLE grant_change_audits IN SHARE ROW EXCLUSIVE MODE'); await tx.$executeRaw`SELECT pg_advisory_xact_lock(${GLOBAL_LOCK})`;
    if (await journalDbOutcome(tx, journal) !== 'full') refuse('compensation source projection is not exact full state'); if ((await nonTarget(tx)).digest !== journal.prestate.non_target_digest) refuse('non-target digest changed before compensation');
    for (const [i, target] of TARGETS.entries()) { const ids = journal.ids[i]; const before = safeAfter(target, ids.principal_id); const timestamp = new Date(); const reason = `compensation_run=${journal.run_id};original_audit=${ids.create_audit_id};plan_sha256=${journal.plan_sha256}`;
      await tx.grantChangeAudit.create({ data: { id: ids.revoke_audit_id, migrationId: MIGRATION_ID, sourceGitCommit: journal.implementation_commit, operatorId: journal.audit_binding.operator_id, approvalRef: journal.audit_binding.approval_ref, reason, clientId: target.clientId, changeType: 'revoke', expectedGrantVersion: 1, resultingGrantVersion: 2, beforeValue: before, afterValue: Prisma.DbNull, timestamp } }); fault(ctx, `compensation-audit:${target.caller}`);
      await tx.machineAccessGrant.delete({ where: { machineClientId_audienceId: { machineClientId: ids.client_internal_id, audienceId: AUDIENCE_ID } } }); fault(ctx, `compensation-grant:${target.caller}`);
      await tx.machineClient.delete({ where: { id: ids.client_internal_id } }); fault(ctx, `compensation-client:${target.caller}`);
      await tx.machinePrincipal.delete({ where: { id: ids.principal_id } }); fault(ctx, `compensation-principal:${target.caller}`);
    }
    if ((await nonTarget(tx)).digest !== journal.prestate.non_target_digest) refuse('non-target digest changed during compensation');
  }, { isolationLevel: Prisma.TransactionIsolationLevel.Serializable, timeout: 60_000, maxWait: 10_000 });
  fault(ctx, 'compensation-commit-uncertain'); journal.db.tx_state = 'compensated'; journal.db.compensation_state = 'complete'; writeJournal(ctx, journal);
}
function restoreJournalFiles(ctx: Context, journal: Journal): string[] {
  const residual = cleanStageResidue(ctx, journal);
  for (const file of journal.files) {
    try {
      const current = lstatMaybe(file.destination_path); const currentBytes = current?.isFile() && !current.isSymbolicLink() && current.nlink === 1 ? readFileSync(file.destination_path) : null; const currentDigest = currentBytes === null ? null : sha256(currentBytes);
      if (file.preimage.exists) {
        const preimageDigest = file.preimage.sha256!; const currentIsPreimage = current !== null && currentBytes !== null && current.uid === file.preimage.uid && (current.mode & 0o777) === file.preimage.mode && current.size === file.preimage.size && currentDigest === preimageDigest;
        if (file.backup_state === 'pending') { if (!currentIsPreimage || file.install_state !== 'pending') throw new Error('unbacked preimage changed'); file.install_state = 'restored'; writeJournal(ctx, journal); continue; }
        if (file.backup_state === 'removed') { if (!currentIsPreimage || file.install_state !== 'restored') throw new Error('removed backup cannot prove restoration'); continue; }
        if (file.backup_state === 'restored' && lstatMaybe(file.backup_path) === null) { if (!currentIsPreimage || file.install_state !== 'restored') throw new Error('deleted backup cannot prove restoration'); file.backup_state = 'removed'; writeJournal(ctx, journal); continue; }
        const backup = lstatSync(file.backup_path); const bytes = readFileSync(file.backup_path); if (!backup.isFile() || backup.isSymbolicLink() || backup.nlink !== 1 || (backup.mode & 0o777) !== 0o600 || backup.uid !== ctx.expectedUid || backup.size !== file.preimage.size || sha256(bytes) !== preimageDigest) throw new Error('backup provenance mismatch');
        if (!currentIsPreimage) { if (file.installed_sha256 === null || currentDigest !== file.installed_sha256) throw new Error('concurrent destination drift'); const restoreStage = `${file.destination_path}.nsc-stage-${journal.run_id}-restore`; stageAt(restoreStage, bytes); renameSync(restoreStage, file.destination_path); chmodSync(file.destination_path, file.preimage.mode ?? 0o600); syncDirectory(file.destination_path); fault(ctx, `restore-renamed:${file.caller}`); }
        const restored = lstatSync(file.destination_path); if (restored.uid !== file.preimage.uid || (restored.mode & 0o777) !== file.preimage.mode || restored.size !== file.preimage.size || sha256(readFileSync(file.destination_path)) !== preimageDigest) throw new Error('byte-exact restoration failed'); file.backup_state = 'restored'; file.install_state = 'restored';
      } else {
        if (current !== null) { if (currentBytes === null || file.installed_sha256 === null || currentDigest !== file.installed_sha256 || current.uid !== ctx.expectedUid || (current.mode & 0o777) !== 0o600) throw new Error('concurrent destination drift'); unlinkSync(file.destination_path); syncDirectory(file.destination_path); fault(ctx, `restore-unlinked:${file.caller}`); }
        file.install_state = 'restored';
      }
      writeJournal(ctx, journal); fault(ctx, `restore:${file.caller}`);
    } catch { residual.push(`destination:${file.destination_path}`); }
  }
  residual.push(...cleanStageResidue(ctx, journal)); return [...new Set(residual)].sort(ascii);
}
function cleanupRecoveryArtifacts(ctx: Context, journal: Journal): string[] {
  const residual: string[] = [];
  for (const file of journal.files) {
    const observed = lstatMaybe(file.backup_path); if (observed === null) continue;
    try { if (!file.preimage.exists || file.preimage.sha256 === null || !observed.isFile() || observed.isSymbolicLink() || observed.nlink !== 1 || observed.uid !== ctx.expectedUid || (observed.mode & 0o777) !== 0o600 || observed.size !== file.preimage.size || sha256(readFileSync(file.backup_path)) !== file.preimage.sha256) throw new Error('backup provenance mismatch'); unlinkSync(file.backup_path); syncDirectory(file.backup_path); fault(ctx, `backup-deleted:${file.caller}`); file.backup_state = 'removed'; writeJournal(ctx, journal); fault(ctx, `backup-cleanup:${file.caller}`); }
    catch { residual.push(`backup:${file.backup_path}`); }
  }
  residual.push(...cleanStageResidue(ctx, journal));
  return [...new Set(residual)].sort(ascii);
}

async function recover(prisma: PrismaClient, ctx: Context): Promise<void> {
  const journal = readJournal(ctx); const identities = await prisma.$queryRaw<Array<{ database: string; address: string; port: number }>>`SELECT current_database()::text AS database, COALESCE(inet_server_addr()::text, 'local') AS address, inet_server_port()::integer AS port`; if (identities.length !== 1 || !same(identities[0], journal.database_identity)) { if (journal.result !== 'COMMIT_FINALIZED') journal.result = 'RECOVERY_REQUIRED'; journal.residual_coordinates = ['database_identity']; writeJournal(ctx, journal); report('apply', 'OUTCOME_UNKNOWN', journal.plan_sha256, 'RECOVERY_ONLY', { principals: -1, clients: -1, grants: -1, audits: -1, destinations: -1, secrets_generated: 0 }, journal.prestate.non_target_digest, journal.residual_coordinates); process.exitCode = 41; return; }
  if (journal.result === 'COMMIT_FINALIZED') {
    const residual: string[] = [];
    try {
      const terminal = await prisma.$transaction(async (tx) => { await tx.$executeRaw`SELECT pg_advisory_xact_lock(${GLOBAL_LOCK})`; const destinationRuntime = TARGETS.map((target) => destination(ctx.destinations[target.caller], ctx.expectedUid, target)); const approvalBinding = { environment: journal.environment, operator_id: journal.audit_binding.operator_id, approval_ref: journal.audit_binding.approval_ref } as Approval; const targets = await targetState(tx, destinationRuntime, ctx.expectedUid, { implementation: journal.implementation_commit, specRevision: journal.spec_revision }, journal.plan_sha256, approvalBinding); const nt = await nonTarget(tx); const dbOutcome = await journalDbOutcome(tx, journal); return { targets: targets.classification, nonTargetDigest: nt.digest, dbOutcome }; }, { isolationLevel: Prisma.TransactionIsolationLevel.Serializable });
      if (terminal.targets !== 'EXACT_RERUN_NOOP' || terminal.nonTargetDigest !== journal.prestate.non_target_digest || terminal.dbOutcome !== 'full') residual.push('finalized_projection');
    } catch { residual.push('finalized_verification'); }
    if (residual.length === 0) residual.push(...cleanupRecoveryArtifacts(ctx, journal));
    if (residual.length > 0) { journal.residual_coordinates = [...new Set(residual)].sort(ascii); writeJournal(ctx, journal); report('apply', 'ROLLBACK_INCOMPLETE', journal.plan_sha256, 'RECOVERY_FINALIZED', { principals: 0, clients: 0, grants: 0, audits: 0, destinations: -1, secrets_generated: 0 }, journal.prestate.non_target_digest, journal.residual_coordinates); process.exitCode = 40; return; }
    try { removeJournal(ctx); } catch { journal.residual_coordinates = ['recovery_journal_finalization']; if (existsSync(ctx.markerPath)) writeJournal(ctx, journal); report('apply', 'ROLLBACK_INCOMPLETE', journal.plan_sha256, 'RECOVERY_FINALIZED', { principals: 0, clients: 0, grants: 0, audits: 0, destinations: 2, secrets_generated: 0 }, journal.prestate.non_target_digest, journal.residual_coordinates); process.exitCode = 40; return; }
    report('apply', 'RECOVERY_FINALIZED', journal.plan_sha256, 'RECOVERY_FINALIZED', { principals: 0, clients: 0, grants: 0, audits: 0, destinations: 2, secrets_generated: 0 }, journal.prestate.non_target_digest); process.exitCode = 30; return;
  }
  let outcome: 'none' | 'full' | 'partial' | 'compensated';
  try { outcome = await prisma.$transaction(async (tx) => { await tx.$executeRaw`SELECT pg_advisory_xact_lock(${GLOBAL_LOCK})`; return journalDbOutcome(tx, journal); }, { isolationLevel: Prisma.TransactionIsolationLevel.Serializable }); } catch { journal.result = 'RECOVERY_REQUIRED'; journal.db.tx_state = 'unknown'; journal.db.commit_state = 'uncertain'; journal.residual_coordinates = ['database_outcome_query']; writeJournal(ctx, journal); report('apply', 'OUTCOME_UNKNOWN', journal.plan_sha256, 'RECOVERY_ONLY', { principals: -1, clients: -1, grants: -1, audits: -1, destinations: -1, secrets_generated: 0 }, journal.prestate.non_target_digest, journal.residual_coordinates); process.exitCode = 41; return; }
  journal.db.commit_state = outcome === 'compensated' ? 'full' : outcome; writeJournal(ctx, journal);
  if (outcome === 'partial') { journal.result = 'RECOVERY_REQUIRED'; journal.db.tx_state = 'unknown'; journal.residual_coordinates = ['database_partial_projection']; writeJournal(ctx, journal); report('apply', 'OUTCOME_UNKNOWN', journal.plan_sha256, 'RECOVERY_ONLY', { principals: -1, clients: -1, grants: -1, audits: -1, destinations: -1, secrets_generated: 0 }, journal.prestate.non_target_digest, journal.residual_coordinates); process.exitCode = 41; return; }
  let compensated = outcome === 'compensated';
  try { if (outcome === 'full') { await compensate(prisma, ctx, journal); compensated = true; } } catch { journal.result = 'RECOVERY_REQUIRED'; journal.db.compensation_state = 'failed'; journal.residual_coordinates = ['database_compensation']; writeJournal(ctx, journal); report('apply', 'ROLLBACK_INCOMPLETE', journal.plan_sha256, 'RECOVERY_ONLY', { principals: -1, clients: -1, grants: -1, audits: -1, destinations: -1, secrets_generated: 0 }, journal.prestate.non_target_digest, journal.residual_coordinates); process.exitCode = 40; return; }
  const residual = restoreJournalFiles(ctx, journal); if (ctx.faultInjection === 'fail:rollback-verification') residual.push('rollback_verification_injected'); else fault(ctx, 'rollback-verification');
  try { const nt = await nonTarget(prisma); if (nt.digest !== journal.prestate.non_target_digest) residual.push('non_target_digest'); const finalDb = await journalDbOutcome(prisma, journal); if (finalDb !== (compensated ? 'compensated' : 'none')) residual.push('database_prestate'); } catch { residual.push('rollback_verification'); }
  if (residual.length > 0) { journal.result = 'RECOVERY_REQUIRED'; journal.residual_coordinates = [...new Set(residual)].sort(ascii); writeJournal(ctx, journal); report('apply', 'ROLLBACK_INCOMPLETE', journal.plan_sha256, compensated ? 'RECOVERY_COMPENSATED' : 'RECOVERY_ONLY', { principals: compensated ? 2 : 0, clients: compensated ? 2 : 0, grants: compensated ? 2 : 0, audits: compensated ? 2 : 0, destinations: -1, secrets_generated: 0 }, journal.prestate.non_target_digest, journal.residual_coordinates); process.exitCode = 40; return; }
  const finalResidual = cleanupRecoveryArtifacts(ctx, journal);
  if (finalResidual.length > 0) { journal.result = 'RECOVERY_REQUIRED'; journal.residual_coordinates = [...new Set(finalResidual)].sort(ascii); writeJournal(ctx, journal); report('apply', 'ROLLBACK_INCOMPLETE', journal.plan_sha256, compensated ? 'RECOVERY_COMPENSATED' : 'RECOVERY_ONLY', { principals: compensated ? 2 : 0, clients: compensated ? 2 : 0, grants: compensated ? 2 : 0, audits: compensated ? 2 : 0, destinations: 2, secrets_generated: 0 }, journal.prestate.non_target_digest, journal.residual_coordinates); process.exitCode = 40; return; }
  try { removeJournal(ctx); } catch { journal.result = 'RECOVERY_REQUIRED'; journal.residual_coordinates = ['recovery_journal_finalization']; if (existsSync(ctx.markerPath)) writeJournal(ctx, journal); report('apply', 'ROLLBACK_INCOMPLETE', journal.plan_sha256, compensated ? 'RECOVERY_COMPENSATED' : 'RECOVERY_ONLY', { principals: compensated ? 2 : 0, clients: compensated ? 2 : 0, grants: compensated ? 2 : 0, audits: compensated ? 2 : 0, destinations: 2, secrets_generated: 0 }, journal.prestate.non_target_digest, journal.residual_coordinates); process.exitCode = 40; return; }
  report('apply', 'ROLLED_BACK', journal.plan_sha256, compensated ? 'RECOVERY_COMPENSATED' : 'RECOVERY_ONLY', { principals: compensated ? 2 : 0, clients: compensated ? 2 : 0, grants: compensated ? 2 : 0, audits: compensated ? 2 : 0, destinations: 2, secrets_generated: 0 }, journal.prestate.non_target_digest); process.exitCode = 30;
}

async function apply(prisma: PrismaClient, ctx: Context, approved: { plan: Plan; digest: string }, auth: Approval, coordinates: { implementation: string; specRevision: string }): Promise<void> {
  const preliminary = await loadLive(prisma, ctx, coordinates); const currentPlan = buildPlan(preliminary, ctx, coordinates); if (!same(currentPlan, approved.plan)) refuse('plan-to-live drift');
  if (approved.plan.classification === 'EXACT_RERUN_NOOP') {
    const lockedDigest = await prisma.$transaction(async (tx) => { await tx.$executeRawUnsafe('LOCK TABLE auth_audiences IN SHARE MODE'); await tx.$executeRawUnsafe('LOCK TABLE machine_principals IN SHARE ROW EXCLUSIVE MODE'); await tx.$executeRawUnsafe('LOCK TABLE machine_clients IN SHARE ROW EXCLUSIVE MODE'); await tx.$executeRawUnsafe('LOCK TABLE machine_access_grants IN SHARE ROW EXCLUSIVE MODE'); await tx.$executeRawUnsafe('LOCK TABLE grant_change_audits IN SHARE ROW EXCLUSIVE MODE'); await tx.$executeRaw`SELECT pg_advisory_xact_lock(${GLOBAL_LOCK})`; const locked = await loadLive(tx, ctx, coordinates); if (!same(buildPlan(locked, ctx, coordinates), approved.plan)) refuse('NOOP plan-to-live drift inside serializable transaction'); return locked.nonTargetDigest; }, { isolationLevel: Prisma.TransactionIsolationLevel.Serializable, timeout: 60_000, maxWait: 10_000 });
    report('apply', 'NOOP', approved.digest, 'EXACT_RERUN_NOOP', { principals: 0, clients: 0, grants: 0, audits: 0, destinations: 0, secrets_generated: 0 }, lockedDigest); return;
  }
  const pre = preliminary.destinationRuntime; const runId = randomUUID(); const ids = TARGETS.map((target) => ({ caller: target.caller, principal_id: deterministicUuid(runId, `${target.caller}:principal`), client_internal_id: deterministicUuid(runId, `${target.caller}:client`), create_audit_id: deterministicUuid(runId, `${target.caller}:create-audit`), revoke_audit_id: deterministicUuid(runId, `${target.caller}:revoke-audit`) }));
  const journal: Journal = { schema_version: 2, run_id: runId, result: 'APPLY_IN_PROGRESS', spec_id: SPEC_ID, spec_revision: coordinates.specRevision, implementation_commit: coordinates.implementation, plan_sha256: approved.digest, environment: ctx.environment, database_identity: preliminary.databaseIdentity, ids, files: TARGETS.map((target, i) => ({ caller: target.caller, destination_path: pre[i].path, stage_path: `${pre[i].path}.nsc-stage-${runId}-${i}`, backup_path: `${pre[i].path}.nsc-backup-${runId}-${i}`, preimage: { exists: pre[i].exists, mode: pre[i].mode, uid: pre[i].uid, size: pre[i].bytes?.length ?? 0, sha256: pre[i].bytes === null ? null : sha256(pre[i].bytes), managed_keys_absent: true }, installed_sha256: null, backup_state: 'pending', stage_state: 'pending', install_state: 'pending' })), db: { tx_state: 'not_started', commit_state: 'not_attempted', compensation_state: 'not_required' }, audit_binding: { operator_id: auth.operator_id, approval_ref: auth.approval_ref, reason: `spec_blob=${coordinates.specRevision};plan_sha256=${approved.digest};environment=${auth.environment}` }, prestate: { target_classification: 'ABSENT', target_projection: preliminary.targets.safe, non_target_digest: preliminary.nonTargetDigest, non_target_client_count: preliminary.nonTargetCounts.clients, non_target_grant_count: preliminary.nonTargetCounts.grants }, secrets_generated: 0, residual_coordinates: [] };
  const secretValues: string[] = []; const hashes: string[] = []; const installedBytes: Buffer[] = []; let callbackComplete = false;
  try {
    writeJournal(ctx, journal, true); fault(ctx, 'journal-created');
    for (const [i, file] of journal.files.entries()) { if (pre[i].bytes !== null) { writeBackup(file.backup_path, pre[i].bytes); fault(ctx, `backup-created:${file.caller}`); } file.backup_state = pre[i].bytes === null ? 'removed' : 'ready'; writeJournal(ctx, journal); fault(ctx, `backup:${file.caller}`); }
    journal.db.tx_state = 'open'; writeJournal(ctx, journal);
    await prisma.$transaction(async (tx) => {
      await tx.$executeRawUnsafe('LOCK TABLE auth_audiences IN SHARE MODE'); await tx.$executeRawUnsafe('LOCK TABLE machine_principals IN SHARE ROW EXCLUSIVE MODE'); await tx.$executeRawUnsafe('LOCK TABLE machine_clients IN SHARE ROW EXCLUSIVE MODE'); await tx.$executeRawUnsafe('LOCK TABLE machine_access_grants IN SHARE ROW EXCLUSIVE MODE'); await tx.$executeRawUnsafe('LOCK TABLE grant_change_audits IN SHARE ROW EXCLUSIVE MODE'); await tx.$executeRaw`SELECT pg_advisory_xact_lock(${GLOBAL_LOCK})`;
      const locked = await loadLive(tx, ctx, coordinates); if (!same(buildPlan(locked, ctx, coordinates), approved.plan) || !destinationsEqual(pre, locked.destinationRuntime)) refuse('plan-to-live drift inside serializable transaction'); if (locked.nonTargetDigest !== approved.plan.non_target.digest) refuse('non-target digest changed before mutation');
      secretValues.push(randomBytes(32).toString('base64url'), randomBytes(32).toString('base64url')); hashes.push(...secretValues.map(hashSecret)); installedBytes.push(...TARGETS.map((target, i) => destinationBytes(pre[i], target, secretValues[i]))); for (const [i, file] of journal.files.entries()) file.installed_sha256 = sha256(installedBytes[i]); journal.secrets_generated = 2; writeJournal(ctx, journal); fault(ctx, 'secrets-generated');
      for (const [i, target] of TARGETS.entries()) { stageAt(journal.files[i].stage_path, installedBytes[i]); fault(ctx, `stage-created:${target.caller}`); journal.files[i].stage_state = 'ready'; writeJournal(ctx, journal); fault(ctx, `stage:${target.caller}`); }
      await createRows(tx, ctx, journal, hashes); journal.db.tx_state = 'rows_written'; writeJournal(ctx, journal);
      if (ctx.faultInjection === 'drift:precommit-nontarget') await tx.$executeRawUnsafe("UPDATE machine_clients SET allowed_scopes=ARRAY['injected-drift']::text[] WHERE client_id='mc_ssssssssssssssssssssssss'");
      const precommitDigest = await nonTarget(tx); if (precommitDigest.digest !== approved.plan.non_target.digest) refuse('non-target digest changed before commit'); fault(ctx, 'precommit-digest');
      for (const [i, file] of journal.files.entries()) { const current = destination(file.destination_path, ctx.expectedUid, TARGETS[i]); if (!destinationsEqual([pre[i]], [current])) refuse('concurrent destination drift before install'); renameSync(file.stage_path, file.destination_path); syncDirectory(file.destination_path); fault(ctx, `install-renamed:${file.caller}`); file.stage_state = 'removed'; file.install_state = 'installed'; writeJournal(ctx, journal); fault(ctx, `install:${file.caller}`); }
      const after = await loadLive(tx, ctx, coordinates, approved.digest, auth); if (after.targets.classification !== 'EXACT_RERUN_NOOP' || after.nonTargetDigest !== approved.plan.non_target.digest) refuse('precommit complete projection verification failed'); journal.db.tx_state = 'committing'; writeJournal(ctx, journal); callbackComplete = true; fault(ctx, 'before-commit');
    }, { isolationLevel: Prisma.TransactionIsolationLevel.Serializable, timeout: 60_000, maxWait: 10_000 });
    journal.db.tx_state = 'committed'; journal.db.commit_state = 'acknowledged'; writeJournal(ctx, journal); fault(ctx, 'commit-acknowledged');
    if (ctx.faultInjection === 'crash:commit-uncertain') { journal.db.commit_state = 'uncertain'; journal.db.tx_state = 'unknown'; writeJournal(ctx, journal); process.exit(86); }
    fault(ctx, 'postcommit-verification'); const verified = await loadLive(prisma, ctx, coordinates, approved.digest, auth); if (verified.targets.classification !== 'EXACT_RERUN_NOOP' || verified.nonTargetDigest !== approved.plan.non_target.digest || !destinationsEqual(verified.destinationRuntime, TARGETS.map((t) => destination(ctx.destinations[t.caller], ctx.expectedUid, t)))) refuse('known postcommit verification failure');
    fault(ctx, 'verified'); journal.result = 'COMMIT_FINALIZED'; journal.residual_coordinates = []; writeJournal(ctx, journal); fault(ctx, 'finalized');
    const successResidue = cleanupRecoveryArtifacts(ctx, journal); if (successResidue.length > 0) { journal.residual_coordinates = successResidue; writeJournal(ctx, journal); report('apply', 'ROLLBACK_INCOMPLETE', approved.digest, 'RECOVERY_FINALIZED', { principals: 0, clients: 0, grants: 0, audits: 0, destinations: 2, secrets_generated: 2 }, verified.nonTargetDigest, successResidue); process.exitCode = 40; return; }
    try { removeJournal(ctx); } catch { journal.residual_coordinates = ['recovery_journal_finalization']; if (existsSync(ctx.markerPath)) writeJournal(ctx, journal); report('apply', 'ROLLBACK_INCOMPLETE', approved.digest, 'RECOVERY_FINALIZED', { principals: 0, clients: 0, grants: 0, audits: 0, destinations: 2, secrets_generated: 2 }, verified.nonTargetDigest, journal.residual_coordinates); process.exitCode = 40; return; }
    report('apply', 'COMMITTED', approved.digest, 'CREATE', { principals: 2, clients: 2, grants: 2, audits: 2, destinations: 2, secrets_generated: 2 }, verified.nonTargetDigest);
  } catch {
    if (!existsSync(ctx.markerPath)) throw new Refusal('journal creation failed before recoverable mutation');
    if (journal.result !== 'COMMIT_FINALIZED') journal.result = 'RECOVERY_REQUIRED'; if (journal.db.commit_state !== 'acknowledged') { journal.db.tx_state = callbackComplete ? 'unknown' : 'rolled_back'; journal.db.commit_state = callbackComplete ? 'uncertain' : 'none'; } writeJournal(ctx, journal); await recover(prisma, ctx);
  } finally { secretValues.fill(''); hashes.fill(''); for (const bytes of installedBytes) bytes.fill(0); }
}

function descriptor(value: Json): Context {
  const v = object(value, 'conformance descriptor'); exactKeys(v, ['schema_version', 'container_id', 'nonce', 'database_url', 'environment', 'destination_root', 'expected_uid', 'marker_path', 'fault_injection'], 'conformance descriptor'); if (v.schema_version !== 1 || v.environment !== 'disposable-conformance' || typeof v.fault_injection !== 'string' || !/^(?:none|(?:crash|fail|drift):[a-z0-9:-]+)$/.test(v.fault_injection)) refuse('conformance descriptor mismatch');
  const containerId = hex(v.container_id, 64, 'container_id'); const nonce = hex(v.nonce, 64, 'nonce'); const url = text(v.database_url, 'database_url'); const parsed = new URL(url); if (parsed.protocol !== 'postgresql:' || parsed.hostname !== '127.0.0.1' || parsed.pathname !== '/auth_nsc_conformance') refuse('conformance database is not disposable-loopback');
  const inspected = parseUnique(Buffer.from(execFileSync('/usr/local/bin/docker', ['inspect', containerId], { env: { PATH: '/usr/local/bin:/usr/bin:/bin' } })), 'docker inspect', 2 * 1024 * 1024); if (!Array.isArray(inspected) || inspected.length !== 1) refuse('conformance container identity invalid'); const info = object(inspected[0], 'docker inspect entry'); const config = object(info.Config, 'docker Config'); const state = object(info.State, 'docker State'); const host = object(info.HostConfig, 'docker HostConfig'); const network = object(info.NetworkSettings, 'docker NetworkSettings'); const labels = object(config.Labels, 'docker labels'); const ports = object(network.Ports, 'docker ports'); const binding = ports['5432/tcp'];
  if (config.Image !== 'postgres@sha256:57c72fd2a128e416c7fcc499958864df5301e940bca0a56f58fddf30ffc07777' || state.Running !== true || labels['com.mayf3.auth.nsc-conformance'] !== `sha256:${sha256(nonce)}` || host.NetworkMode !== 'bridge' || host.Privileged !== false || !object(host.Tmpfs, 'docker tmpfs')['/var/lib/postgresql/data'] || !Array.isArray(info.Mounts) || info.Mounts.length !== 0 || !Array.isArray(binding) || binding.length !== 1 || object(binding[0], 'docker port binding').HostIp !== '127.0.0.1' || Number(object(binding[0], 'docker port binding').HostPort) !== Number(parsed.port)) refuse('conformance container is not exact disposable PostgreSQL');
  const declaredRoot = resolve(text(v.destination_root, 'destination_root')); const root = realpathSync(declaredRoot); const rootStat = lstatSync(root); if ((!root.startsWith('/tmp/') && !root.startsWith('/private/tmp/')) || !rootStat.isDirectory() || rootStat.isSymbolicLink() || rootStat.nlink < 1) refuse('conformance destination must be an owned temporary directory'); const expectedUid = v.expected_uid; if (!Number.isInteger(expectedUid) || (expectedUid as number) < 0 || rootStat.uid !== expectedUid || (rootStat.mode & 0o777) !== 0o700) refuse('expected_uid or temporary root ownership/mode invalid'); const declaredMarker = resolve(text(v.marker_path, 'marker_path')); if (!declaredMarker.startsWith(`${declaredRoot}/`)) refuse('marker must be under temporary destination root'); const markerPath = resolve(root, declaredMarker.slice(declaredRoot.length + 1)); return { url, environment: 'disposable-conformance', destinations: { 'svc-forum': resolve(root, 'svc-forum/notification-ingress.env'), 'svc-workflow': resolve(root, 'svc-workflow/.env') }, expectedUid: expectedUid as number, markerPath, conformance: true, faultInjection: v.fault_injection };
}
function productionContext(): Context { const environment = text(process.env.AUTH_NOTIFICATION_INGRESS_ENVIRONMENT, 'AUTH_NOTIFICATION_INGRESS_ENVIRONMENT'); if (!/^[a-z0-9][a-z0-9._-]{0,63}$/.test(environment) || environment === 'disposable-conformance') refuse('production environment coordinate invalid'); const url = text(process.env.DATABASE_URL, 'DATABASE_URL'); const expectedUid = Number(execFileSync('/usr/bin/id', ['-u', 'yanfenma'], { encoding: 'utf8' }).trim()); if (!Number.isSafeInteger(expectedUid) || expectedUid < 0) refuse('yanfenma owner identity cannot be resolved'); return { url, environment, destinations: Object.fromEntries(TARGETS.map((t) => [t.caller, t.productionDestination])), expectedUid, markerPath: '/Users/yanfenma/.local/state/auth-service/notification-ingress-phase-b-recovery-v1.json', conformance: false, faultInjection: 'none' }; }
function args(argv: string[]): Record<string, string | true> { const result: Record<string, string | true> = {}; const valued = new Set(['--plan-file', '--plan-sha256', '--approval-fd', '--descriptor-fd', '--conformance-mode']); for (let i = 0; i < argv.length; i += 1) { const key = argv[i]; if (!key.startsWith('--') || Object.hasOwn(result, key)) refuse(`unknown or duplicate argument ${key}`); if (valued.has(key)) { const value = argv[++i]; if (!value || value.startsWith('--')) refuse(`${key} requires value`); result[key] = value; } else if (['--plan', '--apply', '--verify', '--conformance'].includes(key)) result[key] = true; else refuse(`unknown argument ${key}`); } return result; }

async function main(): Promise<void> {
  const a = args(process.argv.slice(2)); const conformanceMode = a['--conformance'] === true; let ctx: Context; let operation: 'plan' | 'apply' | 'verify';
  if (conformanceMode) { if (process.env.DATABASE_URL !== undefined || Object.keys(a).some((k) => !['--conformance', '--descriptor-fd', '--conformance-mode', '--plan-file', '--plan-sha256', '--approval-fd'].includes(k))) refuse('conformance seam contamination'); ctx = descriptor(readFifo(a['--descriptor-fd'] as string | undefined, 'conformance descriptor')); const mode = a['--conformance-mode'] ?? 'plan'; if (!['plan', 'apply', 'verify'].includes(String(mode))) refuse('conformance mode invalid'); operation = mode as typeof operation; }
  else { const selected = ['--plan', '--apply', '--verify'].filter((k) => a[k] === true); if (selected.length > 1) refuse('modes are mutually exclusive'); operation = selected[0] === '--apply' ? 'apply' : selected[0] === '--verify' ? 'verify' : 'plan'; ctx = productionContext(); }
  const common = conformanceMode ? ['--conformance', '--descriptor-fd', '--conformance-mode'] : []; const modeAllowed = operation === 'plan' ? (conformanceMode ? common : ['--plan']) : operation === 'verify' ? [...common, ...(conformanceMode ? [] : ['--verify']), '--plan-file', '--plan-sha256'] : [...common, ...(conformanceMode ? [] : ['--apply']), '--plan-file', '--plan-sha256', '--approval-fd']; if (Object.keys(a).some((key) => !modeAllowed.includes(key))) refuse(`${operation} received a mode-incompatible argument`);
  const coordinates = repoCoordinates(operation === 'apply' && !conformanceMode); const prisma = new PrismaClient({ datasources: { db: { url: ctx.url } } });
  try {
    if (operation === 'apply' && existsSync(ctx.markerPath)) { if (!conformanceMode && process.env.AUTH_NOTIFICATION_INGRESS_PRODUCTION_APPLY !== PROD_CONFIRMATION) refuse('production APPLY confirmation gate absent'); await recover(prisma, ctx); return; }
    if (operation === 'plan') { const live = await loadLive(prisma, ctx, coordinates); const envelope = planEnvelope(buildPlan(live, ctx, coordinates)); process.stdout.write(`${JSON.stringify(canonical(envelope))}\n`); return; }
    const planPath = text(a['--plan-file'], '--plan-file'); const digest = hex(a['--plan-sha256'], 64, '--plan-sha256'); const approved = readPlan(planPath, digest, ctx, coordinates);
    if (operation === 'verify') { const live = await loadLive(prisma, ctx, coordinates); if (live.targets.classification !== 'EXACT_RERUN_NOOP' || !same(buildPlan(live, ctx, coordinates), approved.plan)) refuse('verify detected Audience, target, destination, audit, or non-target drift'); report('verify', 'VERIFIED', approved.digest, 'EXACT_RERUN_NOOP', { principals: 0, clients: 0, grants: 0, audits: 0, destinations: 0, secrets_generated: 0 }, live.nonTargetDigest); return; }
    if (!conformanceMode && process.env.AUTH_NOTIFICATION_INGRESS_PRODUCTION_APPLY !== PROD_CONFIRMATION) refuse('production APPLY confirmation gate absent'); const auth = approval(readFifo(a['--approval-fd'] as string | undefined, 'owner approval'), approved.digest, ctx, coordinates); await apply(prisma, ctx, approved, auth, coordinates);
  } finally { await prisma.$disconnect(); }
}
main().catch((error: unknown) => { const code = typeof error === 'object' && error !== null && 'code' in error && typeof error.code === 'string' && /^[A-Z0-9]{1,16}$/.test(error.code) ? error.code : 'UNCLASSIFIED'; const metaCode = typeof error === 'object' && error !== null && 'meta' in error && typeof error.meta === 'object' && error.meta !== null && 'code' in error.meta && typeof error.meta.code === 'string' && /^[A-Z0-9]{1,16}$/.test(error.meta.code) ? error.meta.code : 'NONE'; const message = error instanceof Refusal ? error.message : `unknown query or operator failure (${code}:${metaCode})`; process.stderr.write(`${JSON.stringify({ schema_version: 1, result: 'REFUSED', error: message })}\n`); process.exitCode = error instanceof Refusal ? 20 : 21; });
